<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hands_On_Day_5_Adnan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unduh Dataset dari Kaggle

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("juhibhojani/house-price")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'house-price' dataset.
Path to dataset files: /kaggle/input/house-price

In [2]:
path + '/house_prices.csv'

'/kaggle/input/house-price/house_prices.csv'

# Baca Dataset Pakai Pandas

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(path + '/house_prices.csv')

In [5]:
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [6]:
# Tipe data object di pandas biasanya digunakan untuk
# tipe data string.
df.dtypes

Index                  int64
Title                 object
Description           object
Amount(in rupees)     object
Price (in rupees)    float64
location              object
Carpet Area           object
Status                object
Floor                 object
Transaction           object
Furnishing            object
facing                object
overlooking           object
Society               object
Bathroom              object
Balcony               object
Car Parking           object
Ownership             object
Super Area            object
Dimensions           float64
Plot Area            float64
dtype: object

# Loop DataFrame

## Iterrows

In [7]:
# Untuk simulasi, kita ambil 5 baris saja secara acak.
df_sampel = df.sample(5)

for index, row in df_sampel.iterrows():
  # Mengeluarkan nilai dari kolom "Title" dan kolom "location".
  print(index, "| ", row["Title"], " | ", row["location"])

11105 |  2 BHK Ready to Occupy Flat for sale in Sambhavnath Upvan Chandkheda  |  ahmedabad
127114 |  1 BHK Ready to Occupy Flat for sale Uttam Nagar West  |  new-delhi
132093 |  3 BHK Ready to Occupy Flat for sale Laxmi Nagar  |  new-delhi
12179 |  2 BHK Ready to Occupy Flat for sale Nava Vadaj  |  ahmedabad
7947 |  3 BHK Ready to Occupy Flat for sale Jagatpur  |  ahmedabad

In [8]:
# Kita coba memodifikasi data sampel tsb, mengganti "location" agar menjadi
# huruf besar semua.
for index, row in df_sampel.iterrows():
  # Menggunakan method .upper() untuk kapitalisasi "location".
  print(row["location"].upper())

AHMEDABAD
NEW-DELHI
NEW-DELHI
AHMEDABAD
AHMEDABAD

# Transformasi Kolom

## Carpet Area

In [9]:
df["Carpet Area"]

0          500 sqft
1          473 sqft
2          779 sqft
3          530 sqft
4          635 sqft
            ...
187526          NaN
187527          NaN
187528    1250 sqft
187529          NaN
187530          NaN
Name: Carpet Area, Length: 187531, dtype: object

In [10]:
df["Carpet Area"] = df["Carpet Area"].apply(
    lambda x: str(x).replace(" sqft", "")
)

In [11]:
df["Carpet Area"]

0          500
1          473
2          779
3          530
4          635
          ...
187526     nan
187527     nan
187528    1250
187529     nan
187530     nan
Name: Carpet Area, Length: 187531, dtype: object