<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hands_on_Data_Collection_Day_11_Adnan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SETUP: Install Required Libraries

In [1]:
print("Installing required libraries...")
!pip install -q pandas numpy requests beautifulsoup4 faker openpyxl gspread oauth2client lxml

import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
from faker import Faker
import json
import warnings
warnings.filterwarnings('ignore')

print("✓ All libraries installed successfully!")
print("=" * 80)

Installing required libraries...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 17.1 MB/s eta 0:00:00
✓ All libraries installed successfully!
================================================================================

## IMPORTING DATA FROM CSV/EXCEL

In [2]:
csv_data = """name,age,city,salary
John Doe,28,Jakarta,5000000
Jane Smith,34,Bandung,7500000
Bob Johnson,45,Surabaya,9000000
Alice Williams,29,Jakarta,6000000
Charlie Brown,38,Medan,8000000"""

print(csv_data)

name,age,city,salary
John Doe,28,Jakarta,5000000
Jane Smith,34,Bandung,7500000
Bob Johnson,45,Surabaya,9000000
Alice Williams,29,Jakarta,6000000
Charlie Brown,38,Medan,8000000

In [3]:
print("\n" + "=" * 80)
print("PART 1: IMPORTING DATA FROM CSV/EXCEL")
print("=" * 80)

# --- Exercise 1.1: Create and Read CSV File ---
print("\n--- Exercise 1.1: Working with CSV Files ---")

# Create sample CSV data
csv_data = """name,age,city,salary
John Doe,28,Jakarta,5000000
Jane Smith,34,Bandung,7500000
Bob Johnson,45,Surabaya,9000000
Alice Williams,29,Jakarta,6000000
Charlie Brown,38,Medan,8000000"""

# Save to file
with open('sample_data.csv', 'w') as f:
    f.write(csv_data)

# Read CSV file
df_csv = pd.read_csv('sample_data.csv')
print("\nCSV Data:")
print(df_csv)
print(f"\nShape: {df_csv.shape}")
print(f"Columns: {list(df_csv.columns)}")
print(f"Data types:\n{df_csv.dtypes}")

================================================================================
PART 1: IMPORTING DATA FROM CSV/EXCEL
================================================================================

--- Exercise 1.1: Working with CSV Files ---

CSV Data:
             name  age      city   salary
0        John Doe   28   Jakarta  5000000
1      Jane Smith   34   Bandung  7500000
2     Bob Johnson   45  Surabaya  9000000
3  Alice Williams   29   Jakarta  6000000
4   Charlie Brown   38     Medan  8000000

Shape: (5, 4)
Columns: ['name', 'age', 'city', 'salary']
Data types:
name      object
age        int64
city      object
salary     int64
dtype: object

In [4]:
# --- Exercise 1.2: Advanced CSV Reading ---
print("\n--- Exercise 1.2: Advanced CSV Parameters ---")

# Read with specific parameters
df_csv_advanced = pd.read_csv(
    'sample_data.csv',
    sep=',',
    encoding='utf-8',
    header=0,
    index_col='name'
)
print("\nCSV with name as index:")
print(df_csv_advanced)

--- Exercise 1.2: Advanced CSV Parameters ---

CSV with name as index:
                age      city   salary
name
John Doe         28   Jakarta  5000000
Jane Smith       34   Bandung  7500000
Bob Johnson      45  Surabaya  9000000
Alice Williams   29   Jakarta  6000000
Charlie Brown    38     Medan  8000000

In [6]:
# --- Exercise 1.3: Create and Read Excel File ---
print("\n--- Exercise 1.3: Working with Excel Files ---")

# Create Excel file with multiple sheets
df_sales = pd.DataFrame({
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'quantity': [10, 50, 30, 15],
    'price': [8000000, 150000, 500000, 2000000]
})

df_customers = pd.DataFrame({
    'customer_name': ['PT ABC', 'PT XYZ', 'CV 123'],
    'location': ['Jakarta', 'Surabaya', 'Bandung'],
    'contact': ['08123456789', '08234567890', '08345678901']
})

# Write to Excel with multiple sheets
with pd.ExcelWriter('sample_data.xlsx', engine='openpyxl') as writer:
    df_sales.to_excel(writer, sheet_name='Sales', index=False)
    df_customers.to_excel(writer, sheet_name='Customers', index=False)


# Customers
df_excel1 = pd.read_excel('sample_data.xlsx', sheet_name='Customers')
print("\nExcel Data (Customer sheet):")
print(df_excel1)

# Read Excel file
df_excel = pd.read_excel('sample_data.xlsx', sheet_name='Sales')
print("\nExcel Data (Sales sheet):")
print(df_excel)

# Read all sheets
excel_file = pd.ExcelFile('sample_data.xlsx')
print(f"\nAvailable sheets: {excel_file.sheet_names}")

--- Exercise 1.3: Working with Excel Files ---

Excel Data (Customer sheet):
  customer_name  location     contact
0        PT ABC   Jakarta  8123456789
1        PT XYZ  Surabaya  8234567890
2        CV 123   Bandung  8345678901

Excel Data (Sales sheet):
    product  quantity    price
0    Laptop        10  8000000
1     Mouse        50   150000
2  Keyboard        30   500000
3   Monitor        15  2000000

Available sheets: ['Sales', 'Customers']

## ACCESSING DATA THROUGH APIs

In [7]:
import requests
import pandas as pd

print("\n" + "=" * 80)
print("PART 2: ACCESSING DATA THROUGH APIs")
print("=" * 80)

# --- Exercise 2.1: Simple GET Request ---
print("\n--- Exercise 2.1: Basic API Request (JSONPlaceholder) ---")

url = 'https://jsonplaceholder.typicode.com/users'
response = requests.get(url)

print(f"Status Code: {response.status_code}")
print(f"Response Time: {response.elapsed.total_seconds():.2f} seconds")

if response.status_code == 200:
    users = response.json()
    df_users = pd.DataFrame(users)
    print(f"\nReceived {len(users)} users")
    print("\nFirst 10 users:")
    print(df_users[['id', 'name', 'email', 'phone']].head(10))
else:
    print(f"Error: {response.status_code}")

================================================================================
PART 2: ACCESSING DATA THROUGH APIs
================================================================================

--- Exercise 2.1: Basic API Request (JSONPlaceholder) ---
Status Code: 200
Response Time: 0.05 seconds

Received 10 users

First 10 users:
   id                      name                      email  \
0   1             Leanne Graham          Sincere@april.biz
1   2              Ervin Howell          Shanna@melissa.tv
2   3          Clementine Bauch         Nathan@yesenia.net
3   4          Patricia Lebsack  Julianne.OConner@kory.org
4   5          Chelsey Dietrich   Lucio_Hettinger@annie.ca
5   6      Mrs. Dennis Schulist    Karley_Dach@jasper.info
6   7           Kurtis Weissnat     Telly.Hoeger@billy.biz
7   8  Nicholas Runolfsdottir V       Sherwood@rosamond.me
8   9           Glenna Reichert    Chaim_McDermott@dana.io
9  10        Clementina DuBuque     Rey.Padberg@karina.biz

                   phone
0  1-770-736-8031 x56442
1    010-692-6593 x09125
2         1-463-123-4447
3      493-170-9623 x156
4          (254)954-1289
5   1-477-935-8478 x6430
6           210.067.6132
7      586.493.6943 x140
8   (775)976-6794 x41206
9           024-648-3804

In [8]:
users

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}},
 {'id': 3,
  'name': 'Clementine Bauch',
  'username': 'Samantha',
  'email': 'Nathan@yesenia.net',
  'address': {'street': 'Douglas Extension',
   'suite': 'Suite 847',
   'city': 'McKenziehaven',
   'zipcode': '59590-4157',
   'geo': {'lat': '-68.6102', 'lng': '-47.0653'}},
  'phone': '1-463-123-4447',
  'website': 'ramiro.info',
  'company': {'name': 'Romaguera-Jacobson',
   'catchPhrase': 'Face to face bifurcated interface',
   'bs': 'e-enable strategic applications'}},
 {'id': 4,
  'name': 'Patricia Lebsack',
  'username': 'Karianne',
  'email': 'Julianne.OConner@kory.org',
  'address': {'street': 'Hoeger Mall',
   'suite': 'Apt. 692',
   'city': 'South Elvis',
   'zipcode': '53919-4257',
   'geo': {'lat': '29.4572', 'lng': '-164.2990'}},
  'phone': '493-170-9623 x156',
  'website': 'kale.biz',
  'company': {'name': 'Robel-Corkery',
   'catchPhrase': 'Multi-tiered zero tolerance productivity',
   'bs': 'transition cutting-edge web services'}},
 {'id': 5,
  'name': 'Chelsey Dietrich',
  'username': 'Kamren',
  'email': 'Lucio_Hettinger@annie.ca',
  'address': {'street': 'Skiles Walks',
   'suite': 'Suite 351',
   'city': 'Roscoeview',
   'zipcode': '33263',
   'geo': {'lat': '-31.8129', 'lng': '62.5342'}},
  'phone': '(254)954-1289',
  'website': 'demarco.info',
  'company': {'name': 'Keebler LLC',
   'catchPhrase': 'User-centric fault-tolerant solution',
   'bs': 'revolutionize end-to-end systems'}},
 {'id': 6,
  'name': 'Mrs. Dennis Schulist',
  'username': 'Leopoldo_Corkery',
  'email': 'Karley_Dach@jasper.info',
  'address': {'street': 'Norberto Crossing',
   'suite': 'Apt. 950',
   'city': 'South Christy',
   'zipcode': '23505-1337',
   'geo': {'lat': '-71.4197', 'lng': '71.7478'}},
  'phone': '1-477-935-8478 x6430',
  'website': 'ola.org',
  'company': {'name': 'Considine-Lockman',
   'catchPhrase': 'Synchronised bottom-line interface',
   'bs': 'e-enable innovative applications'}},
 {'id': 7,
  'name': 'Kurtis Weissnat',
  'username': 'Elwyn.Skiles',
  'email': 'Telly.Hoeger@billy.biz',
  'address': {'street': 'Rex Trail',
   'suite': 'Suite 280',
   'city': 'Howemouth',
   'zipcode': '58804-1099',
   'geo': {'lat': '24.8918', 'lng': '21.8984'}},
  'phone': '210.067.6132',
  'website': 'elvis.io',
  'company': {'name': 'Johns Group',
   'catchPhrase': 'Configurable multimedia task-force',
   'bs': 'generate enterprise e-tailers'}},
 {'id': 8,
  'name': 'Nicholas Runolfsdottir V',
  'username': 'Maxime_Nienow',
  'email': 'Sherwood@rosamond.me',
  'address': {'street': 'Ellsworth Summit',
   'suite': 'Suite 729',
   'city': 'Aliyaview',
   'zipcode': '45169',
   'geo': {'lat': '-14.3990', 'lng': '-120.7677'}},
  'phone': '586.493.6943 x140',
  'website': 'jacynthe.com',
  'company': {'name': 'Abernathy Group',
   'catchPhrase': 'Implemented secondary concept',
   'bs': 'e-enable extensible e-tailers'}},
 {'id': 9,
  'name': 'Glenna Reichert',
  'username': 'Delphine',
  'email': 'Chaim_McDermott@dana.io',
  'address': {'street': 'Dayna Park',
   'suite': 'Suite 449',
   'city': 'Bartholomebury',
   'zipcode': '76495-3109',
   'geo': {'lat': '24.6463', 'lng': '-168.8889'}},
  'phone': '(775)976-6794 x41206',
  'website': 'conrad.com',
  'company': {'name': 'Yost and Sons',
   'catchPhrase': 'Switchable contextually-based project',
   'bs': 'aggregate real-time technologies'}},
 {'id': 10,
  'name': 'Clementina DuBuque',
  'username': 'Moriah.Stanton',
  'email': 'Rey.Padberg@karina.biz',
  'address': {'street': 'Kattie Turnpike',
   'suite': 'Suite 198',
   'city': 'Lebsackbury',
   'zipcode': '31428-2261',
   'geo': {'lat': '-38.2386', 'lng': '57.2232'}},
  'phone': '024-648-3804',
  'website': 'ambrose.net',
  'company': {'name': 'Hoeger LLC',
   'catchPhrase': 'Centralized empowering task-force',
   'bs': 'target end-to-end models'}}]

In [9]:
data_test = pd.DataFrame(users)
data_test

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."
5,6,Mrs. Dennis Schulist,Leopoldo_Corkery,Karley_Dach@jasper.info,"{'street': 'Norberto Crossing', 'suite': 'Apt....",1-477-935-8478 x6430,ola.org,"{'name': 'Considine-Lockman', 'catchPhrase': '..."
6,7,Kurtis Weissnat,Elwyn.Skiles,Telly.Hoeger@billy.biz,"{'street': 'Rex Trail', 'suite': 'Suite 280', ...",210.067.6132,elvis.io,"{'name': 'Johns Group', 'catchPhrase': 'Config..."
7,8,Nicholas Runolfsdottir V,Maxime_Nienow,Sherwood@rosamond.me,"{'street': 'Ellsworth Summit', 'suite': 'Suite...",586.493.6943 x140,jacynthe.com,"{'name': 'Abernathy Group', 'catchPhrase': 'Im..."
8,9,Glenna Reichert,Delphine,Chaim_McDermott@dana.io,"{'street': 'Dayna Park', 'suite': 'Suite 449',...",(775)976-6794 x41206,conrad.com,"{'name': 'Yost and Sons', 'catchPhrase': 'Swit..."
9,10,Clementina DuBuque,Moriah.Stanton,Rey.Padberg@karina.biz,"{'street': 'Kattie Turnpike', 'suite': 'Suite ...",024-648-3804,ambrose.net,"{'name': 'Hoeger LLC', 'catchPhrase': 'Central..."

In [10]:
# --- Exercise 2.2: API with Parameters ---
print("\n--- Exercise 2.2: API Request with Parameters ---")

url_posts = 'https://jsonplaceholder.typicode.com/posts'
params = {'userId': 1, '_limit': 5}
response_posts = requests.get(url_posts, params=params)

if response_posts.status_code == 200:
    posts = response_posts.json()
    df_posts = pd.DataFrame(posts)
    print(f"\nPosts by User 1 (limited to 5):")
    print(df_posts[['id', 'title']])

--- Exercise 2.2: API Request with Parameters ---

Posts by User 1 (limited to 5):
   id                                              title
0   1  sunt aut facere repellat provident occaecati e...
1   2                                       qui est esse
2   3  ea molestias quasi exercitationem repellat qui...
3   4                               eum et est occaecati
4   5                                 nesciunt quas odio

In [11]:
df_posts

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

In [12]:
# --- Exercise 2.3: REST Countries API ---
print("\n--- Exercise 2.3: REST Countries API ---")

url = 'https://jsonplaceholder.typicode.com/users'
response = requests.get(url)

url_countries = 'https://restcountries.com/v3.1/region/europe'
response_countries = requests.get(url_countries)

if response_countries.status_code == 200:
    countries = response_countries.json()

    # Extract relevant information
    country_data = []
    for country in countries:  # First 5 countries
        country_data.append({
            'name': country['name']['common'],
            'capital': country.get('capital', ['N/A'])[0],
            'population': country.get('population', 0),
            'area': country.get('area', 0),
            'region': country.get('region', 'N/A')
        })

    df_countries = pd.DataFrame(country_data)
    print("\nAsian Countries (sample):")
    print(df_countries)

--- Exercise 2.3: REST Countries API ---

Asian Countries (sample):
                      name             capital  population         area  \
0                  Romania           Bucharest    19036031    238391.00
1               Luxembourg          Luxembourg      681973      2586.00
2                   Greece              Athens    10400720    131990.00
3                  Albania              Tirana     2363314     28748.00
4                  Belgium            Brussels    11825551     30528.00
5              Netherlands           Amsterdam    18100436     41865.00
6                   Russia              Moscow   146028325  17098246.00
7                   Jersey        Saint Helier      103267       116.00
8                    Spain              Madrid    49315949    505992.00
9               San Marino  City of San Marino       34132        61.00
10                 Finland            Helsinki     5650325    338455.00
11                  Latvia                Riga     1829000     64559.00
12  Svalbard and Jan Mayen        Longyearbyen        2530     61399.00
13           Faroe Islands            Tórshavn       54885      1393.00
14             Switzerland                Bern     9082848     41284.00
15                 Hungary            Budapest     9539502     93028.00
16                Slovenia           Ljubljana     2130638     20273.00
17                  France               Paris    66351959    543908.00
18                 Andorra    Andorra la Vella       88406       468.00
19         North Macedonia              Skopje     1822612     25713.00
20                Portugal              Lisbon    10749635     92090.00
21                   Italy                Rome    58927633    301336.00
22                 Denmark          Copenhagen     6011488     43094.00
23                 Austria              Vienna     9200931     83871.00
24            Vatican City        Vatican City         882         0.49
25                 Croatia              Zagreb     3866233     56594.00
26                   Malta            Valletta      574250       316.00
27                 Iceland           Reykjavik      391810    103000.00
28                 Czechia              Prague    10882341     78865.00
29                  Monaco              Monaco       38423         2.02
30                 Moldova            Chișinău     2749076     33847.00
31           Åland Islands           Mariehamn       30654      1580.00
32             Isle of Man             Douglas       84530       572.00
33                  Sweden           Stockholm    10605098    450295.00
34                 Germany              Berlin    83491249    357114.00
35               Gibraltar           Gibraltar       38000         6.00
36           Liechtenstein               Vaduz       40900       160.00
37                  Cyprus             Nicosia     1442614      9251.00
38              Montenegro           Podgorica      623327     13812.00
39                 Estonia             Tallinn     1369995     45227.00
40                 Ukraine                Kyiv    32862000    603550.00
41                  Kosovo            Pristina     1585566     10908.00
42          United Kingdom              London    69281437    244376.00
43                Bulgaria               Sofia     6437360    110879.00
44                Guernsey      St. Peter Port       64781        78.00
45               Lithuania             Vilnius     2894886     65300.00
46                Slovakia          Bratislava     5413813     49037.00
47                  Poland              Warsaw    37392000    312679.00
48                  Serbia            Belgrade     6567783     77589.00
49                 Ireland              Dublin     5458600     70273.00
50                 Belarus               Minsk     9109280    207600.00
51                  Norway                Oslo     5606944    386224.00
52  Bosnia and Herzegovina            Sarajevo     3422000     51209.00

    region
0   Europe
1   Europe
2   Europe
3   Europe
4   Europe
5   Europe
6   Europe
7   Europe
8   Europe
9   Europe
10  Europe
11  Europe
12  Europe
13  Europe
14  Europe
15  Europe
16  Europe
17  Europe
18  Europe
19  Europe
20  Europe
21  Europe
22  Europe
23  Europe
24  Europe
25  Europe
26  Europe
27  Europe
28  Europe
29  Europe
30  Europe
31  Europe
32  Europe
33  Europe
34  Europe
35  Europe
36  Europe
37  Europe
38  Europe
39  Europe
40  Europe
41  Europe
42  Europe
43  Europe
44  Europe
45  Europe
46  Europe
47  Europe
48  Europe
49  Europe
50  Europe
51  Europe
52  Europe

In [13]:
df_countries

,name,capital,population,area,region
0,Romania,Bucharest,19036031,238391.00,Europe
1,Luxembourg,Luxembourg,681973,2586.00,Europe
2,Greece,Athens,10400720,131990.00,Europe
3,Albania,Tirana,2363314,28748.00,Europe
4,Belgium,Brussels,11825551,30528.00,Europe
5,Netherlands,Amsterdam,18100436,41865.00,Europe
6,Russia,Moscow,146028325,17098246.00,Europe
7,Jersey,Saint Helier,103267,116.00,Europe
8,Spain,Madrid,49315949,505992.00,Europe
9,San Marino,City of San Marino,34132,61.00,Europe
10,Finland,Helsinki,5650325,338455.00,Europe
11,Latvia,Riga,1829000,64559.00,Europe
12,Svalbard and Jan Mayen,Longyearbyen,2530,61399.00,Europe
13,Faroe Islands,Tórshavn,54885,1393.00,Europe
14,Switzerland,Bern,9082848,41284.00,Europe
15,Hungary,Budapest,9539502,93028.00,Europe
16,Slovenia,Ljubljana,2130638,20273.00,Europe
17,France,Paris,66351959,543908.00,Europe
18,Andorra,Andorra la Vella,88406,468.00,Europe
19,North Macedonia,Skopje,1822612,25713.00,Europe
20,Portugal,Lisbon,10749635,92090.00,Europe
21,Italy,Rome,58927633,301336.00,Europe
22,Denmark,Copenhagen,6011488,43094.00,Europe
23,Austria,Vienna,9200931,83871.00,Europe
24,Vatican City,Vatican City,882,0.49,Europe
25,Croatia,Zagreb,3866233,56594.00,Europe
26,Malta,Valletta,574250,316.00,Europe
27,Iceland,Reykjavik,391810,103000.00,Europe
28,Czechia,Prague,10882341,78865.00,Europe
29,Monaco,Monaco,38423,2.02,Europe
30,Moldova,Chișinău,2749076,33847.00,Europe
31,Åland Islands,Mariehamn,30654,1580.00,Europe
32,Isle of Man,Douglas,84530,572.00,Europe
33,Sweden,Stockholm,10605098,450295.00,Europe
34,Germany,Berlin,83491249,357114.00,Europe
35,Gibraltar,Gibraltar,38000,6.00,Europe
36,Liechtenstein,Vaduz,40900,160.00,Europe
37,Cyprus,Nicosia,1442614,9251.00,Europe
38,Montenegro,Podgorica,623327,13812.00,Europe
39,Estonia,Tallinn,1369995,45227.00,Europe
40,Ukraine,Kyiv,32862000,603550.00,Europe
41,Kosovo,Pristina,1585566,10908.00,Europe
42,United Kingdom,London,69281437,244376.00,Europe
43,Bulgaria,Sofia,6437360,110879.00,Europe
44,Guernsey,St. Peter Port,64781,78.00,Europe
45,Lithuania,Vilnius,2894886,65300.00,Europe
46,Slovakia,Bratislava,5413813,49037.00,Europe
47,Poland,Warsaw,37392000,312679.00,Europe
48,Serbia,Belgrade,6567783,77589.00,Europe
49,Ireland,Dublin,5458600,70273.00,Europe
50,Belarus,Minsk,9109280,207600.00,Europe
51,Norway,Oslo,5606944,386224.00,Europe
52,Bosnia and Herzegovina,Sarajevo,3422000,51209.00,Europe

## DATA QUALITY ISSUES

In [14]:
print("\n" + "=" * 80)
print("PART 4: DATA QUALITY ISSUES")
print("=" * 80)

# --- Exercise 4.1: Create Dataset with Quality Issues ---
print("\n--- Exercise 4.1: Creating Dataset with Quality Issues ---")

# Create messy data
messy_data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10],  # Duplicate ID
    'name': ['John Doe', 'jane smith', 'BOB JOHNSON', None, 'Alice', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Grace'],
    'age': [28, 34, 45, 29, -5, 150, 38, 42, None, 35, 35],  # Invalid ages
    'email': ['john@email.com', 'JANE@EMAIL.COM', 'bob@email', None, 'alice@email.com', 'charlie@email.com', 'david@email.com', 'eve@email.com', 'frank@email.com', 'grace@email.com', 'grace@email.com'],
    'salary': ['5000000', '7500000', 'unknown', '6000000', '8000000', '9000000', None, '7000000', '6500000', '8500000', '8500000'],  # Mixed types
    'hire_date': ['2020-01-15', '2019/03/20', '2018-05-10', '15-06-2021', None, '2020-07-22', '2019-11-30', '2021-02-14', '2020-09-05', '2019-04-18', '2019-04-18'],  # Inconsistent formats
    'department': ['IT', 'it', 'HR', 'IT', 'Finance', 'hr', 'IT', 'Finance', 'HR', 'IT', 'IT']  # Case inconsistency
}

df_messy = pd.DataFrame(messy_data)
print("\nOriginal Messy Data:")
print(df_messy)
print(f"\nData Info:")
print(df_messy.info())

================================================================================
PART 4: DATA QUALITY ISSUES
================================================================================

--- Exercise 4.1: Creating Dataset with Quality Issues ---

Original Messy Data:
    employee_id         name    age              email   salary   hire_date  \
0             1     John Doe   28.0     john@email.com  5000000  2020-01-15
1             2   jane smith   34.0     JANE@EMAIL.COM  7500000  2019/03/20
2             3  BOB JOHNSON   45.0          bob@email  unknown  2018-05-10
3             4         None   29.0               None  6000000  15-06-2021
4             5        Alice   -5.0    alice@email.com  8000000        None
5             6      Charlie  150.0  charlie@email.com  9000000  2020-07-22
6             7        David   38.0    david@email.com     None  2019-11-30
7             8          Eve   42.0      eve@email.com  7000000  2021-02-14
8             9        Frank    NaN    frank@email.com  6500000  2020-09-05
9            10        Grace   35.0    grace@email.com  8500000  2019-04-18
10           10        Grace   35.0    grace@email.com  8500000  2019-04-18

   department
0          IT
1          it
2          HR
3          IT
4     Finance
5          hr
6          IT
7     Finance
8          HR
9          IT
10         IT

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  11 non-null     int64
 1   name         10 non-null     object
 2   age          10 non-null     float64
 3   email        10 non-null     object
 4   salary       10 non-null     object
 5   hire_date    10 non-null     object
 6   department   11 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 748.0+ bytes
None

In [15]:
# --- Exercise 4.2: Identify Missing Values ---
print("\n--- Exercise 4.2: Identifying Missing Values ---")

print("\nMissing Values Count:")
print(df_messy.isnull().sum())

print("\nMissing Values Percentage:")
print((df_messy.isnull().sum() / len(df_messy) * 100).round(2))

# Visualize missing patterns
print("\nRows with missing values:")
print(df_messy[df_messy.isnull().any(axis=1)])

--- Exercise 4.2: Identifying Missing Values ---

Missing Values Count:
employee_id    0
name           1
age            1
email          1
salary         1
hire_date      1
department     0
dtype: int64

Missing Values Percentage:
employee_id    0.00
name           9.09
age            9.09
email          9.09
salary         9.09
hire_date      9.09
department     0.00
dtype: float64

Rows with missing values:
   employee_id   name   age            email   salary   hire_date department
3            4   None  29.0             None  6000000  15-06-2021         IT
4            5  Alice  -5.0  alice@email.com  8000000        None    Finance
6            7  David  38.0  david@email.com     None  2019-11-30         IT
8            9  Frank   NaN  frank@email.com  6500000  2020-09-05         HR

In [16]:
# --- Exercise 4.3: Handle Duplicates ---
print("\n--- Exercise 4.3: Handling Duplicates ---")

print(f"\nNumber of duplicate rows: {df_messy.duplicated().sum()}")
print("\nDuplicate rows:")
print(df_messy[df_messy.duplicated(keep=False)])

# Remove duplicates
df_no_dup = df_messy.drop_duplicates()
print(f"\nAfter removing duplicates: {len(df_no_dup)} rows")

--- Exercise 4.3: Handling Duplicates ---

Number of duplicate rows: 1

Duplicate rows:
    employee_id   name   age            email   salary   hire_date department
9            10  Grace  35.0  grace@email.com  8500000  2019-04-18         IT
10           10  Grace  35.0  grace@email.com  8500000  2019-04-18         IT

After removing duplicates: 10 rows

In [17]:
# --- Exercise 4.4: Data Cleaning Process ---
print("\n--- Exercise 4.4: Comprehensive Data Cleaning ---")

df_clean = df_messy.copy()

# Step 1: Remove duplicates
df_clean = df_clean.drop_duplicates()
print(f"Step 1 - After removing duplicates: {len(df_clean)} rows")

# Step 2: Standardize text fields
df_clean['name'] = df_clean['name'].str.title()  # Title case
df_clean['email'] = df_clean['email'].str.lower()  # Lowercase
df_clean['department'] = df_clean['department'].str.upper()  # Uppercase
print("\nStep 2 - Standardized text fields")

# Step 3: Handle missing values
df_clean['name'].fillna('Unknown', inplace=True)
df_clean['age'].fillna(df_clean['age'].median(), inplace=True)
df_clean['email'].fillna('no-email@company.com', inplace=True)
print(f"\nStep 3 - Filled missing values")

# Step 4: Fix data types
df_clean['salary'] = pd.to_numeric(df_clean['salary'], errors='coerce')
df_clean['salary'].fillna(df_clean['salary'].median(), inplace=True)
print("\nStep 4 - Fixed salary data type")

# Step 5: Fix invalid values (age outliers)
df_clean.loc[df_clean['age'] < 0, 'age'] = df_clean['age'].median()
df_clean.loc[df_clean['age'] > 100, 'age'] = df_clean['age'].median()
print("\nStep 5 - Fixed invalid ages")

# Step 6: Standardize date format
df_clean['hire_date'] = pd.to_datetime(df_clean['hire_date'], errors='coerce', format='mixed')
print("\nStep 6 - Standardized date format")

print("\nCleaned Data:")
print(df_clean)

--- Exercise 4.4: Comprehensive Data Cleaning ---
Step 1 - After removing duplicates: 10 rows

Step 2 - Standardized text fields

Step 3 - Filled missing values

Step 4 - Fixed salary data type

Step 5 - Fixed invalid ages

Step 6 - Standardized date format

Cleaned Data:
   employee_id         name   age                 email     salary  hire_date  \
0            1     John Doe  28.0        john@email.com  5000000.0 2020-01-15
1            2   Jane Smith  34.0        jane@email.com  7500000.0 2019-03-20
2            3  Bob Johnson  45.0             bob@email  7250000.0 2018-05-10
3            4      Unknown  29.0  no-email@company.com  6000000.0 2021-06-15
4            5        Alice  35.0       alice@email.com  8000000.0        NaT
5            6      Charlie  35.0     charlie@email.com  9000000.0 2020-07-22
6            7        David  38.0       david@email.com  7250000.0 2019-11-30
7            8          Eve  42.0         eve@email.com  7000000.0 2021-02-14
8            9        Frank  35.0       frank@email.com  6500000.0 2020-09-05
9           10        Grace  35.0       grace@email.com  8500000.0 2019-04-18

  department
0         IT
1         IT
2         HR
3         IT
4    FINANCE
5         HR
6         IT
7    FINANCE
8         HR
9         IT

In [18]:
# --- Exercise 4.5: Detect Outliers ---
print("\n--- Exercise 4.5: Detecting Outliers ---")

# Create sample data with outliers
np.random.seed(42)
outlier_data = {
    'value': np.concatenate([
        np.random.normal(100, 15, 95),  # Normal data
        [250, 300, 350, 400, 450]  # Outliers
    ])
}
df_outliers = pd.DataFrame(outlier_data)

# Method 1: Z-score
from scipy import stats
df_outliers['z_score'] = np.abs(stats.zscore(df_outliers['value']))
outliers_z = df_outliers[df_outliers['z_score'] > 3]
print(f"\nOutliers detected using Z-score (>3): {len(outliers_z)}")

# Method 2: IQR
Q1 = df_outliers['value'].quantile(0.25)
Q3 = df_outliers['value'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers_iqr = df_outliers[(df_outliers['value'] < lower_bound) |
                            (df_outliers['value'] > upper_bound)]
print(f"Outliers detected using IQR: {len(outliers_iqr)}")
print(f"Bounds: [{lower_bound:.2f}, {upper_bound:.2f}]")

--- Exercise 4.5: Detecting Outliers ---

Outliers detected using Z-score (>3): 4
Outliers detected using IQR: 6
Bounds: [63.47, 138.01]

## CREATING YOUR OWN DATASET

In [19]:
print("\n" + "=" * 80)
print("PART 5: CREATING YOUR OWN DATASET")
print("=" * 80)

# --- Exercise 5.1: Simple Manual Dataset ---
print("\n--- Exercise 5.1: Creating Manual Dataset ---")

manual_dataset = pd.DataFrame({
    'student_id': [1001, 1002, 1003, 1004, 1005],
    'name': ['Ahmad', 'Siti', 'Budi', 'Dewi', 'Eko'],
    'grade': ['A', 'B', 'A', 'C', 'B'],
    'score': [95, 82, 88, 75, 79]
})

print("\nManual Student Dataset:")
print(manual_dataset)

================================================================================
PART 5: CREATING YOUR OWN DATASET
================================================================================

--- Exercise 5.1: Creating Manual Dataset ---

Manual Student Dataset:
   student_id   name grade  score
0        1001  Ahmad     A     95
1        1002   Siti     B     82
2        1003   Budi     A     88
3        1004   Dewi     C     75
4        1005    Eko     B     79

In [20]:
# --- Exercise 5.2: Using Faker for Realistic Data ---
print("\n--- Exercise 5.2: Generating Realistic Data with Faker ---")

fake = Faker('id_ID')  # Indonesian locale
Faker.seed(42)

# Generate customer data
n_customers = 20
customer_data = {
    'customer_id': range(1, n_customers + 1),
    'name': [fake.name() for _ in range(n_customers)],
    'email': [fake.email() for _ in range(n_customers)],
    'phone': [fake.phone_number() for _ in range(n_customers)],
    'address': [fake.address() for _ in range(n_customers)],
    'city': [fake.city() for _ in range(n_customers)],
    'registration_date': [fake.date_between(start_date='-2y', end_date='today')
                          for _ in range(n_customers)]
}

df_customers_fake = pd.DataFrame(customer_data)
print("\nGenerated Customer Data (first 5):")
print(df_customers_fake.head())

--- Exercise 5.2: Generating Realistic Data with Faker ---

Generated Customer Data (first 5):
   customer_id                     name                           email  \
0            1   Balidin Dongoran, S.T.              capa31@example.com
1            2          Darmana Mandala             umaya52@example.com
2            3  Ciaobella Wastuti, M.Pd              hari41@example.net
3            4         Lantar Anggraini  farhunnisaprasasta@example.org
4            5          Among Iswahyudi             rwibowo@example.net

                 phone                                            address  \
0  +62 (0828) 148 9325            Jl. Pasteur No. 93\nGorontalo, BB 40164
1    +62 (88) 095-7015    Jalan KH Amin Jasuta No. 27\nSabang, Aceh 12805
2  +62 (0303) 911-7182  Jl. Rajawali Timur No. 05\nTangerang Selatan, ...
3    +62 (78) 248 9638  Gg. Astana Anyar No. 563\nCilegon, Gorontalo 0...
4     +62-465-787-1331         Jl. Astana Anyar No. 3\nMagelang, KR 45868

            city registration_date
0        Cirebon        2025-06-04
1     Singkawang        2024-10-17
2  Pangkalpinang        2025-04-08
3          Tegal        2025-09-27
4         Madiun        2025-03-18

In [ ]:
# --- Exercise 5.3: Synthetic Dataset for ML ---
print("\n--- Exercise 5.3: Creating Synthetic ML Dataset ---")

from sklearn.datasets import make_classification, make_regression

# Classification dataset
X_class, y_class = make_classification(
    n_samples=100,
    n_features=5,
    n_informative=3,
    n_redundant=1,
    n_classes=2,
    random_state=42
)

df_classification = pd.DataFrame(
    X_class,
    columns=[f'feature_{i+1}' for i in range(X_class.shape[1])]
)
df_classification['target'] = y_class

print("\nClassification Dataset (first 5):")
print(df_classification.head())
print(f"Class distribution:\n{df_classification['target'].value_counts()}")

# Regression dataset
X_reg, y_reg = make_regression(
    n_samples=100,
    n_features=3,
    noise=10,
    random_state=42
)

df_regression = pd.DataFrame(
    X_reg,
    columns=['x1', 'x2', 'x3']
)
df_regression['y'] = y_reg

print("\nRegression Dataset (first 5):")
print(df_regression.head())

In [ ]:
# --- Exercise 5.4: Complex E-commerce Dataset ---
print("\n--- Exercise 5.4: Creating Complex E-commerce Dataset ---")

np.random.seed(42)
fake = Faker('id_ID')
Faker.seed(42)

# Generate products
products = ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphone',
            'Webcam', 'Speaker', 'Microphone', 'USB Cable', 'Hard Drive']

n_transactions = 50
ecommerce_data = {
    'transaction_id': [f'TRX{str(i).zfill(5)}' for i in range(1, n_transactions + 1)],
    'customer_name': [fake.name() for _ in range(n_transactions)],
    'product': np.random.choice(products, n_transactions),
    'quantity': np.random.randint(1, 10, n_transactions),
    'price': np.random.choice([150000, 500000, 2000000, 8000000], n_transactions),
    'date': [fake.date_between(start_date='-1y', end_date='today')
             for _ in range(n_transactions)],
    'payment_method': np.random.choice(['Credit Card', 'Bank Transfer', 'E-wallet'],
                                       n_transactions),
    'status': np.random.choice(['Completed', 'Pending', 'Cancelled'],
                               n_transactions, p=[0.7, 0.2, 0.1])
}

df_ecommerce = pd.DataFrame(ecommerce_data)
df_ecommerce['total_amount'] = df_ecommerce['quantity'] * df_ecommerce['price']

print("\nE-commerce Dataset (first 10):")
print(df_ecommerce.head(10))

print("\nDataset Statistics:")
print(f"Total Transactions: {len(df_ecommerce)}")
print(f"Total Revenue: Rp {df_ecommerce['total_amount'].sum():,.0f}")
print(f"\nTop 3 Products:")
print(df_ecommerce['product'].value_counts().head(3))

In [ ]:
# --- Exercise 5.5: Time Series Dataset ---
print("\n--- Exercise 5.5: Creating Time Series Dataset ---")

# Generate daily sales data
date_range = pd.date_range(start='2024-01-01', end='2024-12-30', freq='D')
n_days = len(date_range)

# Add trend and seasonality
trend = np.linspace(100, 200, n_days)
seasonality = 50 * np.sin(np.arange(n_days) * 2 * np.pi / 365)
noise = np.random.normal(0, 10, n_days)
sales = trend + seasonality + noise

df_timeseries = pd.DataFrame({
    'date': date_range,
    'sales': sales.astype(int),
    'day_of_week': date_range.day_name(),
    'month': date_range.month_name(),
    'is_weekend': date_range.dayofweek.isin([5, 6]).astype(int)
})

print("\nTime Series Dataset (first 10):")
print(df_timeseries.head(10))

print("\nMonthly Average Sales:")
monthly_avg = df_timeseries.groupby('month')['sales'].mean().round(2)
print(monthly_avg)

In [ ]:
# --- Exercise 5.6: Save All Datasets ---
print("\n--- Exercise 5.6: Saving Datasets ---")

# Save to CSV
df_clean.to_csv('cleaned_employees.csv', index=False)
df_customers_fake.to_csv('customers.csv', index=False)
df_ecommerce.to_csv('ecommerce_transactions.csv', index=False)
df_timeseries.to_csv('daily_sales.csv', index=False)

# Save to Excel with multiple sheets
with pd.ExcelWriter('all_datasets.xlsx', engine='openpyxl') as writer:
    df_clean.to_excel(writer, sheet_name='Employees', index=False)
    df_customers_fake.to_excel(writer, sheet_name='Customers', index=False)
    df_ecommerce.to_excel(writer, sheet_name='Ecommerce', index=False)
    df_timeseries.to_excel(writer, sheet_name='TimeSeries', index=False)

In [ ]:
# Generate customer data
n_customers = 10000
customer_data = {
    'customer_id': range(1, n_customers + 1),
    'name': [fake.name() for _ in range(n_customers)],
    'email': [fake.email() for _ in range(n_customers)],
    'phone': [fake.phone_number() for _ in range(n_customers)],
    'address': [fake.address() for _ in range(n_customers)],
    'city': [fake.city() for _ in range(n_customers)],
    'registration_date': [fake.date_between(start_date='-2y', end_date='today')
                          for _ in range(n_customers)]
}

df_customers_fake = pd.DataFrame(customer_data)
print("\nGenerated Customer Data (first 5):")
df_customers_fake

Generated Customer Data (first 5):

,customer_id,name,email,phone,address,city,registration_date
0,1,Taswir Zulaika,amelia14@example.com,+62-612-514-2618,"Jalan Otto Iskandardinata No. 5\nDepok, Kepula...",Mataram,2025-11-04
1,2,Paris Salahudin,gamblangdabukke@example.org,+62 (024) 152 1219,"Gg. Joyoboyo No. 845\nSubulussalam, SG 85801",Bukittinggi,2025-06-20
2,3,Anastasia Maryadi,tina83@example.org,+62-0387-300-6032,"Gang PHH. Mustofa No. 98\nBengkulu, Sumatera U...",Tegal,2025-06-11
3,4,Daliono Siregar,marsudisantoso@example.org,089 795 7377,"Gg. Kapten Muslihat No. 7\nPadangpanjang, LA 8...",Tidore Kepulauan,2025-01-15
4,5,Qori Haryanti,kusumohairyanto@example.com,+62 (641) 089-4520,"Jl. Raya Ujungberung No. 491\nMagelang, KR 58220",Mataram,2025-02-06
...,...,...,...,...,...,...,...
9995,9996,"Gandi Megantara, S.Gz",msimbolon@example.com,+62 (80) 820-1803,"Jalan Soekarno Hatta No. 364\nPariaman, Jambi ...",Batam,2024-07-16
9996,9997,Kusuma Yuliarti,tkusumo@example.com,084 728 3284,"Gg. Ahmad Dahlan No. 245\nPalopo, LA 37275",Banjar,2025-10-22
9997,9998,"Kayun Januar, M.Farm",winarsihcandra@example.net,+62 (343) 986-0466,"Jl. Moch. Toha No. 347\nPalangkaraya, SR 12427",Bitung,2024-03-20
9998,9999,Ibun Aryani,purwantiyosef@example.net,(0507) 992-2765,"Gg. Asia Afrika No. 27\nJayapura, JK 85194",Kota Administrasi Jakarta Utara,2025-04-18
9999,10000,T. Purwadi Januar,balijan37@example.com,083 161 8916,Gg. Gardujati No. 3\nKota Administrasi Jakarta...,Palangkaraya,2024-06-09

In [ ]:
df_customers_fake

,customer_id,name,email,phone,address,city,registration_date
0,1,"Balidin Dongoran, S.T.",capa31@example.com,+62 (0828) 148 9325,"Jl. Pasteur No. 93\nGorontalo, BB 40164",Cirebon,2025-04-02
1,2,Darmana Mandala,umaya52@example.com,+62 (88) 095-7015,"Jalan KH Amin Jasuta No. 27\nSabang, Aceh 12805",Singkawang,2024-08-15
2,3,"Ciaobella Wastuti, M.Pd",hari41@example.net,+62 (0303) 911-7182,"Jl. Rajawali Timur No. 05\nTangerang Selatan, ...",Pangkalpinang,2025-02-04
3,4,Lantar Anggraini,farhunnisaprasasta@example.org,+62 (78) 248 9638,"Gg. Astana Anyar No. 563\nCilegon, Gorontalo 0...",Tegal,2025-07-26
4,5,Among Iswahyudi,rwibowo@example.net,+62-465-787-1331,"Jl. Astana Anyar No. 3\nMagelang, KR 45868",Madiun,2025-01-14
5,6,Daruna Mayasari,yessisimbolon@example.org,+62 (098) 393 0103,"Gg. Jend. Sudirman No. 4\nBima, SN 56981",Bekasi,2024-03-05
6,7,Cut Putri Napitupulu,atmasihotang@example.com,+62 (005) 183 4738,"Jalan Bangka Raya No. 883\nPalangkaraya, YO 95148",Palopo,2024-09-24
7,8,"Sadina Palastri, S.Farm",cahyadi39@example.net,+62 (99) 737 6311,"Gang PHH. Mustofa No. 2\nPadangpanjang, PB 99468",Tomohon,2024-12-13
8,9,Ikin Rahmawati,irwan76@example.net,(056) 670-1065,"Jalan Bangka Raya No. 9\nPangkalpinang, Sulawe...",Salatiga,2024-08-17
9,10,Yessi Ardianto,qmegantara@example.org,+62 (033) 387-2624,"Jl. Tebet Barat Dalam No. 33\nBandar Lampung, ...",Makassar,2025-06-21
10,11,"KH. Capa Anggraini, S.Psi",iriananasyiah@example.com,(0317) 810 8013,"Gang Pacuan Kuda No. 016\nCirebon, Sumatera Ut...",Payakumbuh,2024-11-17
11,12,Eva Pratama,zpadmasari@example.com,+62 (67) 736-0260,"Gang Kendalsari No. 8\nPurwokerto, Sulawesi Te...",Denpasar,2025-04-01
12,13,"Tgk. Baktiono Iswahyudi, S.Sos",entengmelani@example.com,(047) 468 7234,Gang Ciumbuleuit No. 4\nKota Administrasi Jaka...,Jambi,2024-10-30
13,14,Gatot Situmorang,hardiansyahdarmaji@example.org,+62-098-050-0978,"Jl. Veteran No. 58\nPadangpanjang, BE 66909",Kota Administrasi Jakarta Selatan,2026-02-19
14,15,Tgk. Yani Gunawan,widyaanggraini@example.net,082 081 2191,"Gg. Rajawali Barat No. 68\nPasuruan, KI 67065",Kota Administrasi Jakarta Utara,2025-03-30
15,16,"Michelle Nasyiah, S.IP",winarnoprabowo@example.net,+62-0619-399-0916,"Jalan Wonoayu No. 0\nSemarang, BA 62720",Sabang,2024-11-05
16,17,Cindy Puspasari,qnuraini@example.net,085 435 3462,"Jalan Erlangga No. 56\nTomohon, SR 17080",Pematangsiantar,2025-01-18
17,18,Yance Utami,zulaikadartono@example.net,+62 (0751) 079-9118,"Jl. Astana Anyar No. 309\nKendari, JB 19374",Bau-Bau,2024-10-03
18,19,dr. Ratih Nababan,siska51@example.com,+62-842-513-5427,"Jl. Rajawali Timur No. 904\nMojokerto, KS 93149",Tebingtinggi,2024-08-08
19,20,"Betania Gunawan, S.H.",dmanullang@example.org,0849808412,"Gang Kapten Muslihat No. 18\nBalikpapan, Sulaw...",Pasuruan,2025-08-02