<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/practice_DS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world

# Variable

## variable angka

In [4]:
x = 10
salam = "Good morning"

## variable huruf

In [5]:
print(x)
print(salam)
salam

10
Good morning

'Good morning'

#if and else

In [6]:
lampu = "nyala"

if(lampu == "nyala"):
  print("lampu nyala")
else:
  print("lampu mati")

lampu nyala

#if, elif, and else

In [9]:
if(lampu == "nyala"):
  print("lampu nyala")
elif(lampu == "hijau"):
  print("lampu hijau")
else:
  print("lampu mati")

lampu hijau

In [8]:
lampu = "hijau"

#import

In [10]:
import pandas

In [11]:
pandas.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [12]:
import pandas as pd

In [13]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

# input

In [14]:
name = input()

jono

In [15]:
print(name)

jono

In [17]:
umur = input("masukkan umur :")
umur = int(umur)

masukkan umur :30

In [18]:
print(umur)

30

In [20]:
umur = umur + 10
print(umur)

40