<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hands_on_Data_Manipulation_Day_13_Adnan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Library and Load Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler # optional
import warnings
warnings.filterwarnings('ignore')

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_rows', 100)

# Set style for visualizations
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

In [2]:
df = pd.read_csv('Online Sales Data.csv')

In [3]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

## Data Exploration

In [4]:
# --- Basic Information ---
print("\n--- 1.1 Basic Dataset Information ---")

print(f"\n Dataset Shape: {df.shape}")
print(f"   Rows: {df.shape[0]}")
print(f"   Columns: {df.shape[1]}")

print("\n First 10 Rows:")
print(df.head(10))

print("\n Last 5 Rows:")
print(df.tail(5))

print("\n Random Sample (5 rows):")
print(df.sample(5))

print("\n Data Types and Info:")
df.info()

print("\n Statistical Summary:")
print(df.describe())

print("\n Column Names:")
print(list(df.columns))

--- 1.1 Basic Dataset Information ---

 Dataset Shape: (240, 9)
   Rows: 240
   Columns: 9

 First 10 Rows:
   Transaction ID        Date Product Category                 Product Name  \
0           10001  2024-01-01      Electronics                iPhone 14 Pro
1           10002  2024-01-02  Home Appliances             Dyson V11 Vacuum
2           10003  2024-01-03         Clothing             Levi's 501 Jeans
3           10004  2024-01-04            Books            The Da Vinci Code
4           10005  2024-01-05  Beauty Products      Neutrogena Skincare Set
5           10006  2024-01-06           Sports  Wilson Evolution Basketball
6           10007  2024-01-07      Electronics          MacBook Pro 16-inch
7           10008  2024-01-08  Home Appliances         Blueair Classic 480i
8           10009  2024-01-09         Clothing             Nike Air Force 1
9           10010  2024-01-10            Books        Dune by Frank Herbert

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal
5           5       29.99         149.95           Asia    Credit Card
6           1     2499.99        2499.99  North America    Credit Card
7           2      599.99        1199.98         Europe         PayPal
8           6       89.99         539.94           Asia     Debit Card
9           2       25.99          51.98  North America    Credit Card

 Last 5 Rows:
     Transaction ID        Date Product Category  \
235           10236  2024-08-23  Home Appliances
236           10237  2024-08-24         Clothing
237           10238  2024-08-25            Books
238           10239  2024-08-26  Beauty Products
239           10240  2024-08-27           Sports

                                        Product Name  Units Sold  Unit Price  \
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99
236                        Nike Air Force 1 Sneakers           3       90.00
237           The Handmaid's Tale by Margaret Atwood           3       10.99
238             Sunday Riley Luna Sleeping Night Oil           1       55.00
239                       Yeti Rambler 20 oz Tumbler           2       29.99

     Total Revenue         Region Payment Method
235         159.99         Europe         PayPal
236         270.00           Asia     Debit Card
237          32.97  North America    Credit Card
238          55.00         Europe         PayPal
239          59.98           Asia    Credit Card

 Random Sample (5 rows):
    Transaction ID        Date Product Category  \
27           10028  2024-01-28            Books
92           10093  2024-04-02         Clothing
66           10067  2024-03-07      Electronics
19           10020  2024-01-20  Home Appliances
0            10001  2024-01-01      Electronics

                           Product Name  Units Sold  Unit Price  \
27   Pride and Prejudice by Jane Austen           3       12.99
92  Adidas Originals Superstar Sneakers           4       79.99
66                   Samsung QLED 4K TV           1     1199.99
19           Ninja Professional Blender           1       99.99
0                         iPhone 14 Pro           2      999.99

    Total Revenue         Region Payment Method
27          38.97  North America    Credit Card
92         319.96           Asia     Debit Card
66        1199.99  North America    Credit Card
19          99.99         Europe         PayPal
0         1999.98  North America    Credit Card

 Data Types and Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

 Statistical Summary:
       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

 Column Names:
['Transaction ID', 'Date', 'Product Category', 'Product Name', 'Units Sold', 'Unit Price', 'Total Revenue', 'Region', 'Payment Method']

In [5]:
# --- Check for Issues ---
print("\n--- 1.2 Data Quality Check ---")

print("\n Missing Values:")
missing = df.isnull().sum()
if missing.sum() == 0:
    print("   ✓ No missing values!")
else:
    print(missing[missing > 0])

print("\n Duplicates:")
duplicates = df.duplicated().sum()
print(f"   Duplicate rows: {duplicates}")

print("\n Unique Values per Column:")
for col in df.columns:
    unique_count = df[col].nunique()
    print(f"   {col}: {unique_count} unique values")

--- 1.2 Data Quality Check ---

 Missing Values:
   ✓ No missing values!

 Duplicates:
   Duplicate rows: 0

 Unique Values per Column:
   Transaction ID: 240 unique values
   Date: 240 unique values
   Product Category: 6 unique values
   Product Name: 232 unique values
   Units Sold: 7 unique values
   Unit Price: 117 unique values
   Total Revenue: 173 unique values
   Region: 3 unique values
   Payment Method: 3 unique values

In [6]:
# Missing value check
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [7]:
# Duplicate check
df.duplicated().sum()

np.int64(0)

## Filtering Data

In [8]:
# Convert Date to datetime for filtering
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()
df['Day_Name'] = df['Date'].dt.day_name()

In [9]:
# --- Exercise 2.1: Simple Filtering ---
print("\n--- Exercise 2.1: Simple Filtering (Single Condition) ---")

# Filter Electronics products
electronics = df[df['Product Category'] == 'Electronics']
print(f"\n🔍 Electronics Products:")
print(f"   Total transactions: {len(electronics)}")
print(f"   Total revenue: Rp {electronics['Total Revenue'].sum():,.2f}")
print(electronics[['Transaction ID', 'Product Name', 'Total Revenue']].head())

# Filter high-value transactions (> 5,000,000)
high_value = df[df['Total Revenue'] > 5000000]
print(f"\n🔍 High Value Transactions (> USD 5,000,000):")
print(f"   Count: {len(high_value)}")
print(high_value[['Transaction ID', 'Product Category', 'Total Revenue']].head())

# Filter Jakarta region
jakarta_sales = df[df['Region'] == 'Jakarta']
print(f"\n🔍 Jakarta Sales:")
print(f"   Transactions: {len(jakarta_sales)}")
print(f"   Total revenue: USD {jakarta_sales['Total Revenue'].sum():,.2f}")

--- Exercise 2.1: Simple Filtering (Single Condition) ---

🔍 Electronics Products:
   Total transactions: 40
   Total revenue: Rp 34,982.41
    Transaction ID                     Product Name  Total Revenue
0            10001                    iPhone 14 Pro        1999.98
6            10007              MacBook Pro 16-inch        2499.99
12           10013            Samsung Galaxy Tab S8        1499.98
18           10019            Garmin Forerunner 945         999.98
24           10025  Bose QuietComfort 35 Headphones         299.99

🔍 High Value Transactions (> USD 5,000,000):
   Count: 0
Empty DataFrame
Columns: [Transaction ID, Product Category, Total Revenue]
Index: []

🔍 Jakarta Sales:
   Transactions: 0
   Total revenue: USD 0.00

In [10]:
# --- Exercise 2.2: Multiple Filters with AND (&) ---
print("\n--- Exercise 2.2: Multiple Filters with AND (&) ---")

# Electronics in Jakarta
electronics_jakarta = df[(df['Product Category'] == 'Electronics') &
                         (df['Region'] == 'Jakarta')]
print(f"\n🔍 Electronics in Jakarta:")
print(f"   Count: {len(electronics_jakarta)}")
print(electronics_jakarta[['Product Category', 'Region', 'Total Revenue']].head())

# High value Credit Card transactions
high_credit = df[(df['Total Revenue'] > 3000000) &
                 (df['Payment Method'] == 'Credit Card')]
print(f"\n🔍 High Value Credit Card Transactions:")
print(f"   Count: {len(high_credit)}")
print(high_credit[['Total Revenue', 'Payment Method', 'Region']].head())

# More than 10 units sold AND Unit Price > 100,000
bulk_expensive = df[(df['Units Sold'] > 10) & (df['Unit Price'] > 100000)]
print(f"\n🔍 Bulk & Expensive Products (Units > 10 AND Price > 100k):")
print(f"   Count: {len(bulk_expensive)}")
print(bulk_expensive[['Product Name', 'Units Sold', 'Unit Price', 'Total Revenue']].head())

--- Exercise 2.2: Multiple Filters with AND (&) ---

🔍 Electronics in Jakarta:
   Count: 0
Empty DataFrame
Columns: [Product Category, Region, Total Revenue]
Index: []

🔍 High Value Credit Card Transactions:
   Count: 0
Empty DataFrame
Columns: [Total Revenue, Payment Method, Region]
Index: []

🔍 Bulk & Expensive Products (Units > 10 AND Price > 100k):
   Count: 0
Empty DataFrame
Columns: [Product Name, Units Sold, Unit Price, Total Revenue]
Index: []

In [11]:
## Product Category Book & Region north america
df[(df['Product Category'] == 'Books') & (df['Region'] == 'North America')]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Month,Month_Name,Day_Name
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,1,January,Thursday
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card,1,January,Wednesday
15,10016,2024-01-16,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,35.99,107.97,North America,Credit Card,1,January,Tuesday
21,10022,2024-01-22,Books,Gone Girl by Gillian Flynn,2,22.99,45.98,North America,Credit Card,1,January,Monday
27,10028,2024-01-28,Books,Pride and Prejudice by Jane Austen,3,12.99,38.97,North America,Credit Card,1,January,Sunday
33,10034,2024-02-03,Books,1984 by George Orwell,4,19.99,79.96,North America,Credit Card,2,February,Saturday
39,10040,2024-02-09,Books,Harry Potter and the Sorcerer's Stone,3,24.99,74.97,North America,Credit Card,2,February,Friday
45,10046,2024-02-15,Books,Becoming by Michelle Obama,4,32.50,130.00,North America,Credit Card,2,February,Thursday
51,10052,2024-02-21,Books,The Silent Patient by Alex Michaelides,2,26.99,53.98,North America,Credit Card,2,February,Wednesday
57,10058,2024-02-27,Books,Educated by Tara Westover,3,28.00,84.00,North America,Credit Card,2,February,Tuesday
63,10064,2024-03-04,Books,Where the Crawdads Sing by Delia Owens,4,18.99,75.96,North America,Credit Card,3,March,Monday
69,10070,2024-03-10,Books,The Great Gatsby by F. Scott Fitzgerald,2,10.99,21.98,North America,Credit Card,3,March,Sunday
75,10076,2024-03-16,Books,To Kill a Mockingbird by Harper Lee,4,14.99,59.96,North America,Credit Card,3,March,Saturday
81,10082,2024-03-22,Books,The Hobbit by J.R.R. Tolkien,3,12.99,38.97,North America,Credit Card,3,March,Friday
87,10088,2024-03-28,Books,The Catcher in the Rye by J.D. Salinger,4,13.99,55.96,North America,Credit Card,3,March,Thursday
93,10094,2024-04-03,Books,The Alchemist by Paulo Coelho,3,14.99,44.97,North America,Credit Card,4,April,Wednesday
99,10100,2024-04-09,Books,The Power of Now by Eckhart Tolle,2,12.99,25.98,North America,Credit Card,4,April,Tuesday
105,10106,2024-04-15,Books,The Girl on the Train by Paula Hawkins,4,10.99,43.96,North America,Credit Card,4,April,Monday
111,10112,2024-04-21,Books,Sapiens: A Brief History of Humankind by Yuval...,2,18.99,37.98,North America,Credit Card,4,April,Sunday
117,10118,2024-04-27,Books,Atomic Habits by James Clear,4,16.99,67.96,North America,Credit Card,4,April,Saturday
123,10124,2024-05-03,Books,The Subtle Art of Not Giving a F*ck by Mark Ma...,3,14.99,44.97,North America,Credit Card,5,May,Friday
129,10130,2024-05-09,Books,The Four Agreements by Don Miguel Ruiz,2,8.99,17.98,North America,Credit Card,5,May,Thursday
135,10136,2024-05-15,Books,Think and Grow Rich by Napoleon Hill,3,9.99,29.97,North America,Credit Card,5,May,Wednesday
141,10142,2024-05-21,Books,The Power of Habit by Charles Duhigg,2,11.99,23.98,North America,Credit Card,5,May,Tuesday
147,10148,2024-05-27,Books,The Outsiders by S.E. Hinton,3,10.99,32.97,North America,Credit Card,5,May,Monday
153,10154,2024-06-02,Books,The Night Circus by Erin Morgenstern,2,16.99,33.98,North America,Credit Card,6,June,Sunday
159,10160,2024-06-08,Books,The Art of War by Sun Tzu,3,7.99,23.97,North America,Credit Card,6,June,Saturday
165,10166,2024-06-14,Books,The Hunger Games by Suzanne Collins,4,8.99,35.96,North America,Credit Card,6,June,Friday
171,10172,2024-06-20,Books,The Girl with the Dragon Tattoo by Stieg Larsson,2,9.99,19.98,North America,Credit Card,6,June,Thursday
177,10178,2024-06-26,Books,The Sun Also Rises by Ernest Hemingway,3,11.99,35.97,North America,Credit Card,6,June,Wednesday
183,10184,2024-07-02,Books,The Martian by Andy Weir,2,12.99,25.98,North America,Credit Card,7,July,Tuesday
189,10190,2024-07-08,Books,The Catcher in the Rye by J.D. Salinger,3,10.99,32.97,North America,Credit Card,7,July,Monday
195,10196,2024-07-14,Books,The Road by Cormac McCarthy,2,11.99,23.98,North America,Credit Card,7,July,Sunday
201,10202,2024-07-20,Books,The Goldfinch by Donna Tartt,2,14.99,29.98,North America,Credit Card,7,July,Saturday
207,10208,2024-07-26,Books,The Great Alone by Kristin Hannah,3,16.99,50.97,North America,Credit Card,7,July,Friday
213,10214,2024-08-01,Books,The Girl with the Dragon Tattoo by Stieg Larsson,3,10.99,32.97,North America,Credit Card,8,August,Thursday
219,10220,2024-08-07,Books,The Nightingale by Kristin Hannah,2,12.99,25.98,North America,Credit Card,8,August,Wednesday
225,10226,2024-08-13,Books,The Silent Patient by Alex Michaelides,3,26.99,80.97,North America,Credit Card,8,August,Tuesday
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card,8,August,Monday
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,8,August,Sunday

In [12]:
# --- Exercise 2.3: Multiple Filters with OR (|) ---
print("\n--- Exercise 2.3: Multiple Filters with OR (|) ---")

# Jakarta OR Bandung
jakarta_bandung = df[(df['Region'] == 'Jakarta') | (df['Region'] == 'Bandung')]
print(f"\n🔍 Jakarta OR Bandung:")
print(f"   Count: {len(jakarta_bandung)}")
print(f"   Jakarta: {len(df[df['Region'] == 'Jakarta'])}")
print(f"   Bandung: {len(df[df['Region'] == 'Bandung'])}")

# Credit Card OR E-wallet
digital_payment = df[(df['Payment Method'] == 'Credit Card') |
                     (df['Payment Method'] == 'E-wallet')]
print(f"\n🔍 Credit Card OR E-wallet:")
print(f"   Count: {len(digital_payment)}")

--- Exercise 2.3: Multiple Filters with OR (|) ---

🔍 Jakarta OR Bandung:
   Count: 0
   Jakarta: 0
   Bandung: 0

🔍 Credit Card OR E-wallet:
   Count: 120

In [13]:
# --- Exercise 2.4: Complex Boolean Filtering ---
print("\n--- Exercise 2.4: Complex Boolean Filtering ---")

# (Electronics OR Clothing) AND (Jakarta OR Surabaya) AND Revenue > 2M
complex_filter = (
    ((df['Product Category'] == 'Electronics') | (df['Product Category'] == 'Clothing')) &
    ((df['Region'] == 'Jakarta') | (df['Region'] == 'Surabaya')) &
    (df['Total Revenue'] > 2000000)
)

filtered_data = df[complex_filter]
print(f"\n🔍 Complex Filter Results:")
print(f"   (Electronics OR Clothing) AND")
print(f"   (Jakarta OR Surabaya) AND")
print(f"   (Revenue > USD 2,000,000)")
print(f"\n   Count: {len(filtered_data)}")
print(filtered_data[['Product Category', 'Region', 'Total Revenue']].head(10))

--- Exercise 2.4: Complex Boolean Filtering ---

🔍 Complex Filter Results:
   (Electronics OR Clothing) AND
   (Jakarta OR Surabaya) AND
   (Revenue > USD 2,000,000)

   Count: 0
Empty DataFrame
Columns: [Product Category, Region, Total Revenue]
Index: []

In [14]:
# --- Exercise 2.5: Using .isin() ---
print("\n--- Exercise 2.5: Filtering with .isin() ---")

# Multiple regions
selected_regions = df[df['Region'].isin(['Jakarta', 'Bandung', 'Surabaya'])]
print(f"\n🔍 Selected Regions (Jakarta, Bandung, Surabaya):")
print(f"   Count: {len(selected_regions)}")
print(selected_regions['Region'].value_counts())

# Multiple categories
selected_categories = df[df['Product Category'].isin(['Electronics', 'Clothing'])]
print(f"\n🔍 Selected Categories (Electronics, Clothing):")
print(f"   Count: {len(selected_categories)}")
print(selected_categories['Product Category'].value_counts())

--- Exercise 2.5: Filtering with .isin() ---

🔍 Selected Regions (Jakarta, Bandung, Surabaya):
   Count: 0
Series([], Name: count, dtype: int64)

🔍 Selected Categories (Electronics, Clothing):
   Count: 80
Product Category
Electronics    40
Clothing       40
Name: count, dtype: int64

In [15]:
# --- Exercise 2.6: Using .loc[] ---
print("\n--- Exercise 2.6: Filtering with .loc[] ---")

# Select specific columns with filter
jakarta_info = df.loc[df['Region'] == 'Jakarta',
                      ['Date', 'Product Category', 'Total Revenue', 'Payment Method']]
print(f"\n🔍 Jakarta Sales Information:")
print(jakarta_info.head(10))

--- Exercise 2.6: Filtering with .loc[] ---

🔍 Jakarta Sales Information:
Empty DataFrame
Columns: [Date, Product Category, Total Revenue, Payment Method]
Index: []

In [16]:
## payment method using credit card or region north america
df[(df['Payment Method'] == 'Credit Card') | (df['Region'] == 'North America')]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Month,Month_Name,Day_Name
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1,January,Monday
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,1,January,Thursday
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,1,January,Saturday
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card,1,January,Sunday
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card,1,January,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card,8,August,Monday
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card,8,August,Wednesday
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card,8,August,Thursday
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,8,August,Sunday
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,8,August,Tuesday

## Grouping & Aggregation

In [17]:
# --- Exercise 3.1: Simple Grouping ---
print("\n--- Exercise 3.1: Simple Grouping with Single Aggregation ---")

# Total revenue by Product Category
revenue_by_category = df.groupby('Product Category')['Total Revenue'].sum()
print(f"\n Total Revenue by Product Category:")
print(revenue_by_category.sort_values(ascending=False))

# Average revenue by Region
avg_revenue_by_region = df.groupby('Region')['Total Revenue'].mean()
print(f"\n Average Revenue by Region:")
print(avg_revenue_by_region.sort_values(ascending=False).round(2))

# Total units sold by Payment Method
units_by_payment = df.groupby('Payment Method')['Units Sold'].sum()
print(f"\n Total Units Sold by Payment Method:")
print(units_by_payment.sort_values(ascending=False))

--- Exercise 3.1: Simple Grouping with Single Aggregation ---

 Total Revenue by Product Category:
Product Category
Electronics        34982.41
Home Appliances    18646.16
Sports             14326.52
Clothing            8128.93
Beauty Products     2621.90
Books               1861.93
Name: Total Revenue, dtype: float64

 Average Revenue by Region:
Region
North America    460.55
Asia             280.69
Europe           265.85
Name: Total Revenue, dtype: float64

 Total Units Sold by Payment Method:
Payment Method
Credit Card    268
Debit Card     145
PayPal         105
Name: Units Sold, dtype: int64

In [18]:
# --- Exercise 3.2: Grouping with reset_index() ---
print("\n--- Exercise 3.2: Grouping with reset_index() ---")

# Convert to DataFrame
revenue_df = df.groupby('Product Category')['Total Revenue'].sum().reset_index()
revenue_df.columns = ['Product Category', 'Total Revenue']
revenue_df = revenue_df.sort_values('Total Revenue', ascending=False)

print(f"\n Revenue by Category (as DataFrame):")
print(revenue_df)

--- Exercise 3.2: Grouping with reset_index() ---

 Revenue by Category (as DataFrame):
  Product Category  Total Revenue
3      Electronics       34982.41
4  Home Appliances       18646.16
5           Sports       14326.52
2         Clothing        8128.93
0  Beauty Products        2621.90
1            Books        1861.93

In [19]:
# --- Exercise 3.3: Multiple Aggregations ---
print("\n--- Exercise 3.3: Multiple Aggregations on Single Column ---")

# Multiple stats for Total Revenue by Category
category_stats = df.groupby('Product Category')['Total Revenue'].agg([
    'sum', 'mean', 'min', 'max', 'count'
])
category_stats.columns = ['Total', 'Average', 'Min', 'Max', 'Count']
print(f"\n Revenue Statistics by Product Category:")
print(category_stats.round(2))

# Multiple stats by Region
region_stats = df.groupby('Region')['Total Revenue'].agg([
    ('Total_Revenue', 'sum'),
    ('Avg_Revenue', 'mean'),
    ('Transaction_Count', 'count')
])
print(f"\n Sales Statistics by Region:")
print(region_stats.round(2))

--- Exercise 3.3: Multiple Aggregations on Single Column ---

 Revenue Statistics by Product Category:
                     Total  Average    Min      Max  Count
Product Category
Beauty Products    2621.90    65.55   6.50   399.99     40
Books              1861.93    46.55  17.98   130.00     40
Clothing           8128.93   203.22  39.60   539.94     40
Electronics       34982.41   874.56  99.99  3899.99     40
Home Appliances   18646.16   466.15  89.99  2599.98     40
Sports            14326.52   358.16  59.98  1895.00     40

 Sales Statistics by Region:
               Total_Revenue  Avg_Revenue  Transaction_Count
Region
Asia                22455.45       280.69                 80
Europe              21268.06       265.85                 80
North America       36844.34       460.55                 80

In [20]:
# --- Exercise 3.4: Multiple Aggregations on Multiple Columns ---
print("\n--- Exercise 3.4: Aggregating Multiple Columns ---")

# Comprehensive analysis by Category
category_analysis = df.groupby('Product Category').agg({
    'Total Revenue': ['sum', 'mean'],
    'Units Sold': ['sum', 'mean'],
    'Transaction ID': 'count',
    'Unit Price': 'mean'
})

print(f"\n Comprehensive Category Analysis:")
print(category_analysis.round(2))

--- Exercise 3.4: Aggregating Multiple Columns ---

 Comprehensive Category Analysis:
                 Total Revenue         Units Sold       Transaction ID  \
                           sum    mean        sum  mean          count
Product Category
Beauty Products        2621.90   65.55         46  1.15             40
Books                  1861.93   46.55        114  2.85             40
Clothing               8128.93  203.22        145  3.62             40
Electronics           34982.41  874.56         66  1.65             40
Home Appliances       18646.16  466.15         59  1.48             40
Sports                14326.52  358.16         88  2.20             40

                 Unit Price
                       mean
Product Category
Beauty Products       61.62
Books                 16.15
Clothing              67.54
Electronics          691.59
Home Appliances      320.19
Sports               261.28

In [21]:
# --- Exercise 3.5: Custom Named Aggregations ---
print("\n--- Exercise 3.5: Custom Named Aggregations ---")

sales_summary = (
    df.groupby('Product Category')
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Avg_Revenue=('Total Revenue', 'mean'),
        Total_Units=('Units Sold', 'sum'),
        Avg_Units=('Units Sold', 'mean'),
        Transaction_Count=('Transaction ID', 'count'),
        Avg_Price=('Unit Price', 'mean')
    )
    .round(2)
    .sort_values('Total_Revenue', ascending=False)
)

print(f"\n Sales Summary by Product Category:")
print(sales_summary)

--- Exercise 3.5: Custom Named Aggregations ---

 Sales Summary by Product Category:
                  Total_Revenue  Avg_Revenue  Total_Units  Avg_Units  \
Product Category
Electronics            34982.41       874.56           66       1.65
Home Appliances        18646.16       466.15           59       1.48
Sports                 14326.52       358.16           88       2.20
Clothing                8128.93       203.22          145       3.62
Beauty Products         2621.90        65.55           46       1.15
Books                   1861.93        46.55          114       2.85

                  Transaction_Count  Avg_Price
Product Category
Electronics                      40     691.59
Home Appliances                  40     320.19
Sports                           40     261.28
Clothing                         40      67.54
Beauty Products                  40      61.62
Books                            40      16.15

In [22]:
# --- Exercise 3.6: Grouping by Multiple Columns ---
print("\n--- Exercise 3.6: Grouping by Multiple Columns ---")

# Sales by Category and Region
category_region = (
    df.groupby(['Product Category', 'Region'])
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Transaction_Count=('Transaction ID', 'count'),
        Avg_Revenue=('Total Revenue', 'mean')
    )
    .reset_index()
    .sort_values('Total_Revenue', ascending=False)
)

print(f"\n Sales by Category and Region (Top 15):")
print(category_region.head(15))

# Sales by Region and Payment Method
region_payment = (
    df.groupby(['Region', 'Payment Method'])
    ['Total Revenue']
    .sum()
    .reset_index()
    .sort_values('Total Revenue', ascending=False)
)

print(f"\n Sales by Region and Payment Method:")
print(region_payment.head(10))

--- Exercise 3.6: Grouping by Multiple Columns ---

 Sales by Category and Region (Top 15):
  Product Category         Region  Total_Revenue  Transaction_Count  \
3      Electronics  North America       34982.41                 40
4  Home Appliances         Europe       18646.16                 40
5           Sports           Asia       14326.52                 40
2         Clothing           Asia        8128.93                 40
0  Beauty Products         Europe        2621.90                 40
1            Books  North America        1861.93                 40

   Avg_Revenue
3    874.56025
4    466.15400
5    358.16300
2    203.22325
0     65.54750
1     46.54825

 Sales by Region and Payment Method:
          Region Payment Method  Total Revenue
3  North America    Credit Card       36844.34
2         Europe         PayPal       21268.06
0           Asia    Credit Card       14326.52
1           Asia     Debit Card        8128.93

In [23]:
# --- Exercise 3.7: Advanced Grouping ---
print("\n--- Exercise 3.7: Advanced Grouping Analysis ---")

# Monthly sales analysis
monthly_sales = (
    df.groupby('Month_Name')
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Total_Transactions=('Transaction ID', 'count'),
        Total_Units=('Units Sold', 'sum'),
        Avg_Transaction_Value=('Total Revenue', 'mean')
    )
    .round(2)
)

print(f"\n Monthly Sales Analysis:")
print(monthly_sales)

# Best performing products by category
best_products = (
    df.groupby(['Product Category', 'Product Name'])
    ['Total Revenue']
    .sum()
    .reset_index()
    .sort_values('Total Revenue', ascending=False)
)

print(f"\n Top 10 Products by Revenue:")
print(best_products.head(10))

--- Exercise 3.7: Advanced Grouping Analysis ---

 Monthly Sales Analysis:
            Total_Revenue  Total_Transactions  Total_Units  \
Month_Name
April            12451.69                  30           65
August            7278.11                  27           52
February         10803.37                  29           77
January          14548.32                  31           68
July              6797.08                  31           53
June              7384.55                  30           61
March            12849.24                  31           82
May               8455.49                  31           60

            Avg_Transaction_Value
Month_Name
April                      415.06
August                     269.56
February                   372.53
January                    469.30
July                       219.26
June                       246.15
March                      414.49
May                        272.76

 Top 10 Products by Revenue:
    Product Category                       Product Name  Total Revenue
130      Electronics                Canon EOS R5 Camera        3899.99
182  Home Appliances                         LG OLED TV        2599.98
142      Electronics                MacBook Pro 16-inch        2499.99
123      Electronics          Apple MacBook Pro 16-inch        2399.00
154      Electronics                      iPhone 14 Pro        1999.98
217           Sports                       Peloton Bike        1895.00
138      Electronics             HP Spectre x360 Laptop        1599.99
190  Home Appliances                         Roomba i7+        1599.98
149      Electronics  Samsung Odyssey G9 Gaming Monitor        1499.99
146      Electronics              Samsung Galaxy Tab S8        1499.98

## Sorting

In [24]:
# --- Exercise 4.1: Simple Sorting ---
print("\n--- Exercise 4.1: Simple Sorting (Ascending) ---")

# Sort by Total Revenue (ascending)
sorted_asc = df.sort_values('Total Revenue')
print(f"\n Lowest Revenue Transactions:")
print(sorted_asc[['Transaction ID', 'Product Category', 'Total Revenue']].head(10))

--- Exercise 4.1: Simple Sorting (Ascending) ---

 Lowest Revenue Transactions:
     Transaction ID Product Category  Total Revenue
106           10107  Beauty Products           6.50
226           10227  Beauty Products           6.70
136           10137  Beauty Products           6.80
112           10113  Beauty Products          15.00
166           10167  Beauty Products          16.99
129           10130            Books          17.98
190           10191  Beauty Products          18.00
171           10172            Books          19.98
231           10232            Books          19.98
69            10070            Books          21.98

In [25]:
# --- Exercise 4.2: Descending Sort ---
print("\n--- Exercise 4.2: Sorting (Descending) ---")

# Sort by Total Revenue (descending)
sorted_desc = df.sort_values('Total Revenue', ascending=False)
print(f"\n Highest Revenue Transactions:")
print(sorted_desc[['Transaction ID', 'Product Category', 'Total Revenue']].head(10))

# Sort by Units Sold (descending)
sorted_units = df.sort_values('Units Sold', ascending=False)
print(f"\n Highest Units Sold:")
print(sorted_units[['Product Name', 'Units Sold', 'Total Revenue']].head(10))

--- Exercise 4.2: Sorting (Descending) ---

 Highest Revenue Transactions:
     Transaction ID Product Category  Total Revenue
102           10103      Electronics        3899.99
85            10086  Home Appliances        2599.98
6             10007      Electronics        2499.99
216           10217      Electronics        2399.00
0             10001      Electronics        1999.98
35            10036           Sports        1895.00
72            10073      Electronics        1599.99
37            10038  Home Appliances        1599.98
138           10139      Electronics        1499.99
12            10013      Electronics        1499.98

 Highest Units Sold:
                      Product Name  Units Sold  Total Revenue
62       Hanes ComfortSoft T-Shirt          10          99.90
8                 Nike Air Force 1           6         539.94
83  Spalding NBA Street Basketball           6         149.94
47            Yeti Rambler Tumbler           6         239.94
98  Gap Essential Crewneck T-Shirt           6         119.94
53      Titleist Pro V1 Golf Balls           5         249.95
32   Under Armour HeatGear T-Shirt           5         149.95
5      Wilson Evolution Basketball           5         149.95
74       Tommy Hilfiger Polo Shirt           5         249.95
56       Calvin Klein Boxer Briefs           5         149.95

In [26]:
# --- Exercise 4.3: Sorting by Multiple Columns ---
print("\n--- Exercise 4.3: Sorting by Multiple Columns ---")

# Sort by Category (asc) then Revenue (desc)
multi_sort = df.sort_values(['Product Category', 'Total Revenue'],
                            ascending=[True, False])
print(f"\n Sorted by Category and Revenue:")
print(multi_sort[['Product Category', 'Product Name', 'Total Revenue']].head(15))

# Sort by Region (asc), Payment Method (asc), Revenue (desc)
complex_sort = df.sort_values(['Region', 'Payment Method', 'Total Revenue'],
                              ascending=[True, True, False])
print(f"\n Sorted by Region, Payment, and Revenue:")
print(complex_sort[['Region', 'Payment Method', 'Total Revenue']].head(15))

--- Exercise 4.3: Sorting by Multiple Columns ---

 Sorted by Category and Revenue:
    Product Category                           Product Name  Total Revenue
16   Beauty Products            Dyson Supersonic Hair Dryer         399.99
184  Beauty Products     La Mer Crème de la Mer Moisturizer         190.00
10   Beauty Products                   Chanel No. 5 Perfume         129.99
196  Beauty Products          Tom Ford Black Orchid Perfume         125.00
40   Beauty Products     Estee Lauder Advanced Night Repair         105.00
88   Beauty Products                Sunday Riley Good Genes         105.00
64   Beauty Products               Lancome La Vie Est Belle         102.00
82   Beauty Products          Charlotte Tilbury Magic Cream         100.00
4    Beauty Products                Neutrogena Skincare Set          89.99
100  Beauty Products  Kiehl's Midnight Recovery Concentrate          82.00
34   Beauty Products               L'Oreal Revitalift Serum          79.98
208  Beauty Products    Caudalie Vinoperfect Radiance Serum          79.00
70   Beauty Products       Drunk Elephant C-Firma Day Serum          78.00
94   Beauty Products                 Tatcha The Water Cream          68.00
178  Beauty Products    First Aid Beauty Ultra Repair Cream          68.00

 Sorted by Region, Payment, and Revenue:
    Region Payment Method  Total Revenue
35    Asia    Credit Card        1895.00
95    Asia    Credit Card         999.99
173   Asia    Credit Card         699.99
113   Asia    Credit Card         689.85
221   Asia    Credit Card         599.99
65    Asia    Credit Card         599.98
11    Asia    Credit Card         599.97
185   Asia    Credit Card         499.95
17    Asia    Credit Card         479.96
197   Asia    Credit Card         449.99
107   Asia    Credit Card         399.99
203   Asia    Credit Card         399.99
71    Asia    Credit Card         389.97
215   Asia    Credit Card         349.99
59    Asia    Credit Card         349.00

In [27]:
# --- Exercise 4.4: Sorting Aggregated Data ---
print("\n--- Exercise 4.4: Sorting Aggregated Results ---")

# Top 5 categories by revenue
top_categories = (
    df.groupby('Product Category')['Total Revenue']
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

print(f"\n Top 5 Categories by Revenue:")
print(top_categories)

# Top regions by transaction count
top_regions = (
    df.groupby('Region')['Transaction ID']
    .count()
    .sort_values(ascending=False)
)

print(f"\n Regions by Transaction Count:")
print(top_regions)

--- Exercise 4.4: Sorting Aggregated Results ---

 Top 5 Categories by Revenue:
Product Category
Electronics        34982.41
Home Appliances    18646.16
Sports             14326.52
Clothing            8128.93
Beauty Products     2621.90
Name: Total Revenue, dtype: float64

 Regions by Transaction Count:
Region
Asia             80
Europe           80
North America    80
Name: Transaction ID, dtype: int64

In [28]:
# --- Exercise 4.5: Finding Top and Bottom Performers ---
print("\n--- Exercise 4.5: Top and Bottom Performers ---")

# Top 5 and Bottom 5 transactions
print(f"\n Top 5 Transactions by Revenue:")
print(df.nlargest(5, 'Total Revenue')[['Transaction ID', 'Product Category', 'Total Revenue']])

print(f"\n Bottom 5 Transactions by Revenue:")
print(df.nsmallest(5, 'Total Revenue')[['Transaction ID', 'Product Category', 'Total Revenue']])

--- Exercise 4.5: Top and Bottom Performers ---

 Top 5 Transactions by Revenue:
     Transaction ID Product Category  Total Revenue
102           10103      Electronics        3899.99
85            10086  Home Appliances        2599.98
6             10007      Electronics        2499.99
216           10217      Electronics        2399.00
0             10001      Electronics        1999.98

 Bottom 5 Transactions by Revenue:
     Transaction ID Product Category  Total Revenue
106           10107  Beauty Products           6.50
226           10227  Beauty Products           6.70
136           10137  Beauty Products           6.80
112           10113  Beauty Products          15.00
166           10167  Beauty Products          16.99

## Pivot Tables

In [29]:
# --- Exercise 5.1: Simple Pivot Table ---
print("\n--- Exercise 5.1: Simple Pivot Table ---")

# Average revenue by Category and Region
pivot_simple = df.pivot_table(
    values='Total Revenue',
    index='Product Category',
    columns='Region',
    aggfunc='mean'
)

print(f"\n📊 Average Revenue by Category and Region:")
print(pivot_simple.round(2))

--- Exercise 5.1: Simple Pivot Table ---

📊 Average Revenue by Category and Region:
Region              Asia  Europe  North America
Product Category
Beauty Products      NaN   65.55            NaN
Books                NaN     NaN          46.55
Clothing          203.22     NaN            NaN
Electronics          NaN     NaN         874.56
Home Appliances      NaN  466.15            NaN
Sports            358.16     NaN            NaN

In [30]:
# --- Exercise 5.2: Pivot with Sum ---
print("\n--- Exercise 5.2: Pivot Table with Sum ---")

# Total revenue by Category and Payment Method
pivot_sum = df.pivot_table(
    values='Total Revenue',
    index='Product Category',
    columns='Payment Method',
    aggfunc='sum',
    fill_value=0
)

print(f"\n📊 Total Revenue by Category and Payment Method:")
print(pivot_sum.round(2))

--- Exercise 5.2: Pivot Table with Sum ---

📊 Total Revenue by Category and Payment Method:
Payment Method    Credit Card  Debit Card    PayPal
Product Category
Beauty Products          0.00        0.00   2621.90
Books                 1861.93        0.00      0.00
Clothing                 0.00     8128.93      0.00
Electronics          34982.41        0.00      0.00
Home Appliances          0.00        0.00  18646.16
Sports               14326.52        0.00      0.00

In [31]:
# --- Exercise 5.3: Pivot with Multiple Values ---
print("\n--- Exercise 5.3: Pivot with Multiple Metrics ---")

# Revenue and Units by Category and Region
pivot_multi = df.pivot_table(
    values=['Total Revenue', 'Units Sold'],
    index='Product Category',
    columns='Region',
    aggfunc={'Total Revenue': 'sum', 'Units Sold': 'sum'},
    fill_value=0
)

print(f"\n📊 Revenue and Units by Category and Region:")
print(pivot_multi)

--- Exercise 5.3: Pivot with Multiple Metrics ---

📊 Revenue and Units by Category and Region:
                 Total Revenue                         Units Sold         \
Region                    Asia    Europe North America       Asia Europe
Product Category
Beauty Products           0.00   2621.90          0.00          0     46
Books                     0.00      0.00       1861.93          0      0
Clothing               8128.93      0.00          0.00        145      0
Electronics               0.00      0.00      34982.41          0      0
Home Appliances           0.00  18646.16          0.00          0     59
Sports                14326.52      0.00          0.00         88      0


Region           North America
Product Category
Beauty Products              0
Books                      114
Clothing                     0
Electronics                 66
Home Appliances              0
Sports                       0

In [32]:
# --- Exercise 5.4: Pivot with Margins (Totals) ---
print("\n--- Exercise 5.4: Pivot with Row and Column Totals ---")

# Revenue with totals
pivot_margins = df.pivot_table(
    values='Total Revenue',
    index='Product Category',
    columns='Region',
    aggfunc='sum',
    fill_value=0,
    margins=True,
    margins_name='TOTAL'
)

print(f"\n📊 Revenue by Category and Region (with Totals):")
print(pivot_margins.round(2))

--- Exercise 5.4: Pivot with Row and Column Totals ---

📊 Revenue by Category and Region (with Totals):
Region                Asia    Europe  North America     TOTAL
Product Category
Beauty Products       0.00   2621.90           0.00   2621.90
Books                 0.00      0.00        1861.93   1861.93
Clothing           8128.93      0.00           0.00   8128.93
Electronics           0.00      0.00       34982.41  34982.41
Home Appliances       0.00  18646.16           0.00  18646.16
Sports            14326.52      0.00           0.00  14326.52
TOTAL             22455.45  21268.06       36844.34  80567.85

In [33]:
# --- Exercise 5.5: Complex Pivot ---
print("\n--- Exercise 5.5: Complex Pivot Table ---")

# Multi-level pivot
pivot_complex = df.pivot_table(
    values='Total Revenue',
    index=['Product Category', 'Payment Method'],
    columns='Region',
    aggfunc=['sum', 'mean', 'count'],
    fill_value=0
)

print(f"\n📊 Complex Pivot (Category & Payment vs Region):")
print(pivot_complex.head(20))

--- Exercise 5.5: Complex Pivot Table ---

📊 Complex Pivot (Category & Payment vs Region):
                                      sum                               mean  \
Region                               Asia    Europe North America       Asia
Product Category Payment Method
Beauty Products  PayPal              0.00   2621.90          0.00    0.00000
Books            Credit Card         0.00      0.00       1861.93    0.00000
Clothing         Debit Card       8128.93      0.00          0.00  203.22325
Electronics      Credit Card         0.00      0.00      34982.41    0.00000
Home Appliances  PayPal              0.00  18646.16          0.00    0.00000
Sports           Credit Card     14326.52      0.00          0.00  358.16300

                                                        count         \
Region                             Europe North America  Asia Europe
Product Category Payment Method
Beauty Products  PayPal           65.5475       0.00000     0     40
Books            Credit Card       0.0000      46.54825     0      0
Clothing         Debit Card        0.0000       0.00000    40      0
Electronics      Credit Card       0.0000     874.56025     0      0
Home Appliances  PayPal          466.1540       0.00000     0     40
Sports           Credit Card       0.0000       0.00000    40      0


Region                          North America
Product Category Payment Method
Beauty Products  PayPal                     0
Books            Credit Card               40
Clothing         Debit Card                 0
Electronics      Credit Card               40
Home Appliances  PayPal                     0
Sports           Credit Card                0

In [34]:
# --- Exercise 5.6: Monthly Pivot ---
print("\n--- Exercise 5.6: Time-based Pivot Table ---")

# Monthly revenue by Category
pivot_monthly = df.pivot_table(
    values='Total Revenue',
    index='Month_Name',
    columns='Product Category',
    aggfunc='sum',
    fill_value=0
)

# Reorder months
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']
pivot_monthly = pivot_monthly.reindex([m for m in month_order if m in pivot_monthly.index])

print(f"\n📊 Monthly Revenue by Product Category:")
print(pivot_monthly.round(2))

print("\n" + "=" * 60)
print("💡 PIVOT TABLE BENEFITS:")
print("   ✓ Quickly summarize data from multiple angles")
print("   ✓ Easy comparison across categories")
print("   ✓ Add totals with margins=True")
print("=" * 60)

--- Exercise 5.6: Time-based Pivot Table ---

📊 Monthly Revenue by Product Category:
Product Category  Beauty Products   Books  Clothing  Electronics  \
Month_Name
January                    699.95  308.86   1789.84      7999.90
February                   331.98  422.91   1284.81      2899.88
March                      417.00  252.83   1009.76      4499.90
April                      201.48  220.85    769.80      6709.91
May                        127.30  149.87    829.88      4198.96
June                       209.49  149.86    579.45      3599.93
July                       464.00  163.88   1095.48      2006.97
August                     170.70  192.87    769.91      3066.96

Product Category  Home Appliances   Sports
Month_Name
January                   2169.94  1579.83
February                  2869.92  2993.87
March                     5059.91  1609.84
April                     1989.85  2559.80
May                       1989.82  1159.66
June                      1479.89  1365.93
July                      1417.87  1648.88
August                    1668.96  1408.71

============================================================
💡 PIVOT TABLE BENEFITS:
   ✓ Quickly summarize data from multiple angles
   ✓ Easy comparison across categories
   ✓ Add totals with margins=True
============================================================

## Cross Tabulation

In [35]:
# --- Exercise 6.1: Simple Crosstab ---
print("\n--- Exercise 6.1: Simple Cross Tabulation ---")

# Count of transactions by Category and Region
crosstab_simple = pd.crosstab(df['Product Category'], df['Region'])
print(f"\n📊 Transaction Count by Category and Region:")
print(crosstab_simple)

--- Exercise 6.1: Simple Cross Tabulation ---

📊 Transaction Count by Category and Region:
Region            Asia  Europe  North America
Product Category
Beauty Products      0      40              0
Books                0       0             40
Clothing            40       0              0
Electronics          0       0             40
Home Appliances      0      40              0
Sports              40       0              0

In [36]:
# --- Exercise 6.2: Crosstab with Margins ---
print("\n--- Exercise 6.2: Crosstab with Totals ---")

# With row and column totals
crosstab_margins = pd.crosstab(
    df['Product Category'],
    df['Region'],
    margins=True,
    margins_name='TOTAL'
)

print(f"\n📊 Transaction Count (with Totals):")
print(crosstab_margins)

--- Exercise 6.2: Crosstab with Totals ---

📊 Transaction Count (with Totals):
Region            Asia  Europe  North America  TOTAL
Product Category
Beauty Products      0      40              0     40
Books                0       0             40     40
Clothing            40       0              0     40
Electronics          0       0             40     40
Home Appliances      0      40              0     40
Sports              40       0              0     40
TOTAL               80      80             80    240

In [37]:
# --- Exercise 6.3: Crosstab with Percentages ---
print("\n--- Exercise 6.3: Crosstab with Percentages ---")

# Row percentages (% of each category in each region)
crosstab_row_pct = pd.crosstab(
    df['Product Category'],
    df['Region'],
    normalize='index'
) * 100

print(f"\n📊 Category Distribution by Region (Row %):")
print(crosstab_row_pct.round(2))

# Column percentages (% of each region's transactions by category)
crosstab_col_pct = pd.crosstab(
    df['Product Category'],
    df['Region'],
    normalize='columns'
) * 100

print(f"\n📊 Region Distribution by Category (Column %):")
print(crosstab_col_pct.round(2))

# Overall percentages
crosstab_all_pct = pd.crosstab(
    df['Product Category'],
    df['Region'],
    normalize='all'
) * 100

print(f"\n📊 Overall Distribution (%):")
print(crosstab_all_pct.round(2))

--- Exercise 6.3: Crosstab with Percentages ---

📊 Category Distribution by Region (Row %):
Region             Asia  Europe  North America
Product Category
Beauty Products     0.0   100.0            0.0
Books               0.0     0.0          100.0
Clothing          100.0     0.0            0.0
Electronics         0.0     0.0          100.0
Home Appliances     0.0   100.0            0.0
Sports            100.0     0.0            0.0

📊 Region Distribution by Category (Column %):
Region            Asia  Europe  North America
Product Category
Beauty Products    0.0    50.0            0.0
Books              0.0     0.0           50.0
Clothing          50.0     0.0            0.0
Electronics        0.0     0.0           50.0
Home Appliances    0.0    50.0            0.0
Sports            50.0     0.0            0.0

📊 Overall Distribution (%):
Region             Asia  Europe  North America
Product Category
Beauty Products    0.00   16.67           0.00
Books              0.00    0.00          16.67
Clothing          16.67    0.00           0.00
Electronics        0.00    0.00          16.67
Home Appliances    0.00   16.67           0.00
Sports            16.67    0.00           0.00

In [38]:
# --- Exercise 6.4: Crosstab with Values ---
print("\n--- Exercise 6.4: Crosstab with Aggregated Values ---")

# Total revenue by Category and Payment Method
crosstab_revenue = pd.crosstab(
    df['Product Category'],
    df['Payment Method'],
    values=df['Total Revenue'],
    aggfunc='sum'
)

print(f"\n📊 Total Revenue by Category and Payment Method:")
print(crosstab_revenue.fillna(0).round(2))

# Average revenue by Region and Payment Method
crosstab_avg = pd.crosstab(
    df['Region'],
    df['Payment Method'],
    values=df['Total Revenue'],
    aggfunc='mean'
)

print(f"\n📊 Average Revenue by Region and Payment Method:")
print(crosstab_avg.fillna(0).round(2))

--- Exercise 6.4: Crosstab with Aggregated Values ---

📊 Total Revenue by Category and Payment Method:
Payment Method    Credit Card  Debit Card    PayPal
Product Category
Beauty Products          0.00        0.00   2621.90
Books                 1861.93        0.00      0.00
Clothing                 0.00     8128.93      0.00
Electronics          34982.41        0.00      0.00
Home Appliances          0.00        0.00  18646.16
Sports               14326.52        0.00      0.00

📊 Average Revenue by Region and Payment Method:
Payment Method  Credit Card  Debit Card  PayPal
Region
Asia                 358.16      203.22    0.00
Europe                 0.00        0.00  265.85
North America        460.55        0.00    0.00

In [39]:
# --- Exercise 6.5: Multi-level Crosstab ---
print("\n--- Exercise 6.5: Multi-level Cross Tabulation ---")

# Crosstab with multiple row variables
crosstab_multi = pd.crosstab(
    [df['Product Category'], df['Payment Method']],
    df['Region'],
    margins=True
)

print(f"\n📊 Multi-level Crosstab (Category & Payment vs Region):")
print(crosstab_multi.head(20))

--- Exercise 6.5: Multi-level Cross Tabulation ---

📊 Multi-level Crosstab (Category & Payment vs Region):
Region                           Asia  Europe  North America  All
Product Category Payment Method
Beauty Products  PayPal             0      40              0   40
Books            Credit Card        0       0             40   40
Clothing         Debit Card        40       0              0   40
Electronics      Credit Card        0       0             40   40
Home Appliances  PayPal             0      40              0   40
Sports           Credit Card       40       0              0   40
All                                80      80             80  240

In [40]:
# --- Exercise 6.6: Payment Method Analysis ---
print("\n--- Exercise 6.6: Payment Method Preference by Category ---")

payment_category = pd.crosstab(
    df['Payment Method'],
    df['Product Category'],
    normalize='columns'
) * 100

print(f"\n📊 Payment Method Preference by Category (%):")
print(payment_category.round(2))

print("\n" + "=" * 60)
print("💡 CROSSTAB vs PIVOT:")
print("   CROSSTAB: Best for frequency counts and categorical analysis")
print("   PIVOT: Best for aggregating numerical values")
print("=" * 60)

--- Exercise 6.6: Payment Method Preference by Category ---

📊 Payment Method Preference by Category (%):
Product Category  Beauty Products  Books  Clothing  Electronics  \
Payment Method
Credit Card                   0.0  100.0       0.0        100.0
Debit Card                    0.0    0.0     100.0          0.0
PayPal                      100.0    0.0       0.0          0.0

Product Category  Home Appliances  Sports
Payment Method
Credit Card                   0.0   100.0
Debit Card                    0.0     0.0
PayPal                      100.0     0.0

============================================================
💡 CROSSTAB vs PIVOT:
   CROSSTAB: Best for frequency counts and categorical analysis
   PIVOT: Best for aggregating numerical values
============================================================

## Appending Data Frame

In [41]:
# --- Exercise 7.1: Create Multiple DataFrames ---
print("\n--- Exercise 7.1: Simulating Multiple Data Sources ---")

# Split data by month to simulate monthly data files
jan_data = df[df['Month'] == 1].copy()
feb_data = df[df['Month'] == 2].copy()
mar_data = df[df['Month'] == 3].copy()

print(f"\n📊 January Data: {len(jan_data)} transactions")
print(jan_data.head())

print(f"\n📊 February Data: {len(feb_data)} transactions")
print(feb_data.head())

print(f"\n📊 March Data: {len(mar_data)} transactions")
print(mar_data.head())

--- Exercise 7.1: Simulating Multiple Data Sources ---

📊 January Data: 31 transactions
   Transaction ID       Date Product Category             Product Name  \
0           10001 2024-01-01      Electronics            iPhone 14 Pro
1           10002 2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003 2024-01-03         Clothing         Levi's 501 Jeans
3           10004 2024-01-04            Books        The Da Vinci Code
4           10005 2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method  Month  \
0           2      999.99        1999.98  North America    Credit Card      1
1           1      499.99         499.99         Europe         PayPal      1
2           3       69.99         209.97           Asia     Debit Card      1
3           4       15.99          63.96  North America    Credit Card      1
4           1       89.99          89.99         Europe         PayPal      1

  Month_Name   Day_Name
0    January     Monday
1    January    Tuesday
2    January  Wednesday
3    January   Thursday
4    January     Friday

📊 February Data: 29 transactions
    Transaction ID       Date Product Category                   Product Name  \
31           10032 2024-02-01  Home Appliances                Instant Pot Duo
32           10033 2024-02-02         Clothing  Under Armour HeatGear T-Shirt
33           10034 2024-02-03            Books          1984 by George Orwell
34           10035 2024-02-04  Beauty Products       L'Oreal Revitalift Serum
35           10036 2024-02-05           Sports                   Peloton Bike

    Units Sold  Unit Price  Total Revenue         Region Payment Method  \
31           3       89.99         269.97         Europe         PayPal
32           5       29.99         149.95           Asia     Debit Card
33           4       19.99          79.96  North America    Credit Card
34           2       39.99          79.98         Europe         PayPal
35           1     1895.00        1895.00           Asia    Credit Card

    Month Month_Name  Day_Name
31      2   February  Thursday
32      2   February    Friday
33      2   February  Saturday
34      2   February    Sunday
35      2   February    Monday

📊 March Data: 31 transactions
    Transaction ID       Date Product Category  \
60           10061 2024-03-01      Electronics
61           10062 2024-03-02  Home Appliances
62           10063 2024-03-03         Clothing
63           10064 2024-03-04            Books
64           10065 2024-03-05  Beauty Products

                              Product Name  Units Sold  Unit Price  \
60                         Nintendo Switch           3      299.99
61                    Philips Airfryer XXL           2      199.99
62               Hanes ComfortSoft T-Shirt          10        9.99
63  Where the Crawdads Sing by Delia Owens           4       18.99
64                Lancome La Vie Est Belle           1      102.00

    Total Revenue         Region Payment Method  Month Month_Name  Day_Name
60         899.97  North America    Credit Card      3      March    Friday
61         399.98         Europe         PayPal      3      March  Saturday
62          99.90           Asia     Debit Card      3      March    Sunday
63          75.96  North America    Credit Card      3      March    Monday
64         102.00         Europe         PayPal      3      March   Tuesday

In [42]:
# --- Exercise 7.2: Vertical Stacking (Appending) ---
print("\n--- Exercise 7.2: Appending DataFrames (Vertical Stack) ---")

# Append January and February
q1_partial = pd.concat([jan_data, feb_data])
print(f"\n📊 January + February: {len(q1_partial)} transactions")

--- Exercise 7.2: Appending DataFrames (Vertical Stack) ---

📊 January + February: 60 transactions

In [43]:
# --- Exercise 7.3: Append Multiple DataFrames ---
print("\n--- Exercise 7.3: Appending Multiple DataFrames ---")

# Combine all Q1 data
q1_data = pd.concat([jan_data, feb_data, mar_data], ignore_index=True)
print(f"\n📊 Q1 Combined Data: {len(q1_data)} transactions")
print(f"   Total Revenue: Rp {q1_data['Total Revenue'].sum():,.2f}")

# Verify monthly breakdown
print(f"\n📊 Monthly Breakdown:")
print(q1_data.groupby('Month_Name')['Transaction ID'].count())

--- Exercise 7.3: Appending Multiple DataFrames ---

📊 Q1 Combined Data: 91 transactions
   Total Revenue: Rp 38,200.93

📊 Monthly Breakdown:
Month_Name
February    29
January     31
March       31
Name: Transaction ID, dtype: int64

In [44]:
# --- Exercise 7.4: Append with Different Columns ---
print("\n--- Exercise 7.4: Appending with Additional Columns ---")

# Create new data with extra column
apr_data = df[df['Month'] == 4].copy()
apr_data['Discount_Applied'] = np.random.choice(['Yes', 'No'], len(apr_data))

print(f"\n📊 April Data (with Discount column):")
print(apr_data[['Transaction ID', 'Total Revenue', 'Discount_Applied']].head())

# Append with different columns
combined_with_new_col = pd.concat([q1_data, apr_data], ignore_index=True)
print(f"\n📊 Combined Q1 + April: {len(combined_with_new_col)} transactions")
print(f"   Missing values in Discount_Applied: {combined_with_new_col['Discount_Applied'].isnull().sum()}")

--- Exercise 7.4: Appending with Additional Columns ---

📊 April Data (with Discount column):
    Transaction ID  Total Revenue Discount_Applied
91           10092         179.99              Yes
92           10093         319.96               No
93           10094          44.97              Yes
94           10095          68.00               No
95           10096         999.99              Yes

📊 Combined Q1 + April: 121 transactions
   Missing values in Discount_Applied: 91

In [45]:
# --- Exercise 7.5: Practical Use Case ---
print("\n--- Exercise 7.5: Practical Monthly Report Compilation ---")

# Simulate monthly sales reports
monthly_summary = []

for month in sorted(df['Month'].unique()):
    month_df = df[df['Month'] == month]
    summary = {
        'Month': month_df['Month_Name'].iloc[0],
        'Total_Transactions': len(month_df),
        'Total_Revenue': month_df['Total Revenue'].sum(),
        'Avg_Revenue': month_df['Total Revenue'].mean(),
        'Total_Units': month_df['Units Sold'].sum()
    }
    monthly_summary.append(summary)

monthly_report = pd.DataFrame(monthly_summary)
print(f"\n📊 Monthly Sales Report:")
print(monthly_report.round(2))

--- Exercise 7.5: Practical Monthly Report Compilation ---

📊 Monthly Sales Report:
      Month  Total_Transactions  Total_Revenue  Avg_Revenue  Total_Units
0   January                  31       14548.32       469.30           68
1  February                  29       10803.37       372.53           77
2     March                  31       12849.24       414.49           82
3     April                  30       12451.69       415.06           65
4       May                  31        8455.49       272.76           60
5      June                  30        7384.55       246.15           61
6      July                  31        6797.08       219.26           53
7    August                  27        7278.11       269.56           52

## Working with Data Frame

In [46]:
# Date column already converted, let's explore it
print("\n--- Exercise 8.1: Date Components Extraction ---")

# Extract various date components
df['Year'] = df['Date'].dt.year
df['Quarter'] = df['Date'].dt.quarter
df['Week'] = df['Date'].dt.isocalendar().week
df['Day'] = df['Date'].dt.day
df['Day_of_Week'] = df['Date'].dt.dayofweek  # Monday=0, Sunday=6
df['Is_Weekend'] = df['Day_of_Week'].isin([5, 6]).astype(int)
df['Day_of_Year'] = df['Date'].dt.dayofyear

print(f"\n📅 Date Components (first 10 rows):")
print(df[['Date', 'Year', 'Quarter', 'Month_Name', 'Day', 'Day_Name', 'Week', 'Is_Weekend']].head(10))

--- Exercise 8.1: Date Components Extraction ---

📅 Date Components (first 10 rows):
        Date  Year  Quarter Month_Name  Day   Day_Name  Week  Is_Weekend
0 2024-01-01  2024        1    January    1     Monday     1           0
1 2024-01-02  2024        1    January    2    Tuesday     1           0
2 2024-01-03  2024        1    January    3  Wednesday     1           0
3 2024-01-04  2024        1    January    4   Thursday     1           0
4 2024-01-05  2024        1    January    5     Friday     1           0
5 2024-01-06  2024        1    January    6   Saturday     1           1
6 2024-01-07  2024        1    January    7     Sunday     1           1
7 2024-01-08  2024        1    January    8     Monday     2           0
8 2024-01-09  2024        1    January    9    Tuesday     2           0
9 2024-01-10  2024        1    January   10  Wednesday     2           0

In [47]:
# --- Exercise 8.2: Weekday vs Weekend Analysis ---
print("\n--- Exercise 8.2: Weekday vs Weekend Sales Analysis ---")

weekday_weekend = df.groupby('Is_Weekend').agg({
    'Total Revenue': ['sum', 'mean', 'count'],
    'Units Sold': 'sum'
})

weekday_weekend.index = ['Weekday', 'Weekend']
print(f"\n📅 Weekday vs Weekend Comparison:")
print(weekday_weekend.round(2))

# Sales by day of week
day_analysis = (
    df.groupby('Day_Name')
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Avg_Revenue=('Total Revenue', 'mean'),
        Transaction_Count=('Transaction ID', 'count')
    )
    .round(2)
)

# Reorder by day of week
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
day_analysis = day_analysis.reindex([d for d in day_order if d in day_analysis.index])

print(f"\n📅 Sales by Day of Week:")
print(day_analysis)

--- Exercise 8.2: Weekday vs Weekend Sales Analysis ---

📅 Weekday vs Weekend Comparison:
        Total Revenue               Units Sold
                  sum    mean count        sum
Weekday      57920.53  336.75   172        356
Weekend      22647.32  333.05    68        162

📅 Sales by Day of Week:
           Total_Revenue  Avg_Revenue  Transaction_Count
Day_Name
Monday          12253.35       350.10                 35
Tuesday         13518.34       386.24                 35
Wednesday       10402.14       305.95                 34
Thursday         8827.96       259.65                 34
Friday          12918.74       379.96                 34
Saturday        11494.02       338.06                 34
Sunday          11153.30       328.04                 34

In [48]:
# --- Exercise 8.3: Monthly Trends ---
print("\n--- Exercise 8.3: Monthly Sales Trends ---")

monthly_trend = (
    df.groupby('Month_Name')
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Avg_Revenue=('Total Revenue', 'mean'),
        Total_Transactions=('Transaction ID', 'count'),
        Total_Units=('Units Sold', 'sum')
    )
    .round(2)
)

print(f"\n📅 Monthly Sales Trend:")
print(monthly_trend)

--- Exercise 8.3: Monthly Sales Trends ---

📅 Monthly Sales Trend:
            Total_Revenue  Avg_Revenue  Total_Transactions  Total_Units
Month_Name
April            12451.69       415.06                  30           65
August            7278.11       269.56                  27           52
February         10803.37       372.53                  29           77
January          14548.32       469.30                  31           68
July              6797.08       219.26                  31           53
June              7384.55       246.15                  30           61
March            12849.24       414.49                  31           82
May               8455.49       272.76                  31           60

In [49]:
# --- Exercise 8.4: Weekly Aggregation ---
print("\n--- Exercise 8.4: Weekly Sales Analysis ---")

weekly_sales = (
    df.groupby('Week')
    .agg(
        Total_Revenue=('Total Revenue', 'sum'),
        Transaction_Count=('Transaction ID', 'count')
    )
    .round(2)
)

print(f"\n📅 Weekly Sales (first 10 weeks):")
print(weekly_sales.head(10))

--- Exercise 8.4: Weekly Sales Analysis ---

📅 Weekly Sales (first 10 weeks):
      Total_Revenue  Transaction_Count
Week
1           5513.83                  7
2           4211.83                  7
3           2767.84                  7
4           1064.87                  7
5           1569.81                  7
6           5374.86                  7
7           2361.86                  7
8           1857.84                  7
9           2028.80                  7
10          2899.84                  7

In [50]:
# --- Exercise 8.5: Date Filtering ---
print("\n--- Exercise 8.5: Time-based Filtering ---")

# Filter Q1 2024
q1_filter = df[(df['Date'] >= '2024-01-01') & (df['Date'] <= '2024-03-31')]
print(f"\n📅 Q1 2024 Sales:")
print(f"   Transactions: {len(q1_filter)}")
print(f"   Revenue: Rp {q1_filter['Total Revenue'].sum():,.2f}")

# Filter first week of each month
first_week = df[df['Day'] <= 7]
print(f"\n📅 First Week of Months:")
print(f"   Transactions: {len(first_week)}")
print(f"   Revenue: Rp {first_week['Total Revenue'].sum():,.2f}")

# Filter weekends only
weekend_sales = df[df['Is_Weekend'] == 1]
print(f"\n📅 Weekend Sales:")
print(f"   Transactions: {len(weekend_sales)}")
print(f"   Revenue: Rp {weekend_sales['Total Revenue'].sum():,.2f}")

--- Exercise 8.5: Time-based Filtering ---

📅 Q1 2024 Sales:
   Transactions: 91
   Revenue: Rp 38,200.93

📅 First Week of Months:
   Transactions: 56
   Revenue: Rp 26,115.76

📅 Weekend Sales:
   Transactions: 68
   Revenue: Rp 22,647.32

In [51]:
# --- Exercise 8.6: Time-based Features ---
print("\n--- Exercise 8.6: Creating Time-based Features ---")

# Create useful features
df['Is_Month_Start'] = df['Date'].dt.is_month_start.astype(int)
df['Is_Month_End'] = df['Date'].dt.is_month_end.astype(int)
df['Is_Quarter_Start'] = df['Date'].dt.is_quarter_start.astype(int)
df['Is_Quarter_End'] = df['Date'].dt.is_quarter_end.astype(int)

print(f"\n📅 Time-based Features (sample):")
print(df[['Date', 'Is_Month_Start', 'Is_Month_End', 'Is_Quarter_Start', 'Is_Quarter_End']].head(10))

# Check month-end performance
month_end_perf = df.groupby('Is_Month_End')['Total Revenue'].agg(['sum', 'mean', 'count'])
month_end_perf.index = ['Not Month End', 'Month End']
print(f"\n📅 Month-End Performance:")
print(month_end_perf.round(2))

--- Exercise 8.6: Creating Time-based Features ---

📅 Time-based Features (sample):
        Date  Is_Month_Start  Is_Month_End  Is_Quarter_Start  Is_Quarter_End
0 2024-01-01               1             0                 1               0
1 2024-01-02               0             0                 0               0
2 2024-01-03               0             0                 0               0
3 2024-01-04               0             0                 0               0
4 2024-01-05               0             0                 0               0
5 2024-01-06               0             0                 0               0
6 2024-01-07               0             0                 0               0
7 2024-01-08               0             0                 0               0
8 2024-01-09               0             0                 0               0
9 2024-01-10               0             0                 0               0

📅 Month-End Performance:
                    sum    mean  count
Not Month End  77279.34  331.67    233
Month End       3288.51  469.79      7

## Feature Scaling (Optional)

In [52]:
# --- Exercise 9.1: Understanding Data Scale ---
print("\n--- Exercise 9.1: Understanding Different Scales ---")

# Select numerical features
numerical_features = ['Units Sold', 'Unit Price', 'Total Revenue']

print(f"\n📊 Original Data Statistics:")
print(df[numerical_features].describe().round(2))

print(f"\n💡 Notice the different scales:")
print(f"   Units Sold: {df['Units Sold'].min()} - {df['Units Sold'].max()}")
print(f"   Unit Price: {df['Unit Price'].min():.2f} - {df['Unit Price'].max():.2f}")
print(f"   Total Revenue: {df['Total Revenue'].min():.2f} - {df['Total Revenue'].max():.2f}")

--- Exercise 9.1: Understanding Different Scales ---

📊 Original Data Statistics:
       Units Sold  Unit Price  Total Revenue
count      240.00      240.00         240.00
mean         2.16      236.40         335.70
std          1.32      429.45         485.80
min          1.00        6.50           6.50
25%          1.00       29.50          62.96
50%          2.00       89.99         179.97
75%          3.00      249.99         399.22
max         10.00     3899.99        3899.99

💡 Notice the different scales:
   Units Sold: 1 - 10
   Unit Price: 6.50 - 3899.99
   Total Revenue: 6.50 - 3899.99

In [53]:
# --- Exercise 9.2: StandardScaler (Z-Score Normalization) ---
print("\n--- Exercise 9.2: StandardScaler (Mean=0, Std=1) ---")

# Create copy for StandardScaler
df_standard = df.copy()

# Initialize and fit StandardScaler
scaler_standard = StandardScaler()
df_standard[numerical_features] = scaler_standard.fit_transform(df[numerical_features])

print(f"\n📊 After StandardScaler:")
print(df_standard[numerical_features].describe().round(2))

print(f"\n💡 StandardScaler Characteristics:")
print(f"   - Mean ≈ 0")
print(f"   - Standard Deviation = 1")
print(f"   - Preserves outliers")
print(f"   - Good for normally distributed data")

# Compare original vs scaled
comparison_standard = pd.DataFrame({
    'Original_Revenue': df['Total Revenue'].head(10),
    'Scaled_Revenue': df_standard['Total Revenue'].head(10),
    'Original_Units': df['Units Sold'].head(10),
    'Scaled_Units': df_standard['Units Sold'].head(10)
})

print(f"\n📊 Comparison (first 10 transactions):")
print(comparison_standard.round(3))

--- Exercise 9.2: StandardScaler (Mean=0, Std=1) ---

📊 After StandardScaler:
       Units Sold  Unit Price  Total Revenue
count      240.00      240.00         240.00
mean         0.00        0.00           0.00
std          1.00        1.00           1.00
min         -0.88       -0.54          -0.68
25%         -0.88       -0.48          -0.56
50%         -0.12       -0.34          -0.32
75%          0.64        0.03           0.13
max          5.94        8.55           7.35

💡 StandardScaler Characteristics:
   - Mean ≈ 0
   - Standard Deviation = 1
   - Preserves outliers
   - Good for normally distributed data

📊 Comparison (first 10 transactions):
   Original_Revenue  Scaled_Revenue  Original_Units  Scaled_Units
0           1999.98           3.433               2        -0.120
1            499.99           0.339               1        -0.878
2            209.97          -0.259               3         0.638
3             63.96          -0.561               4         1.396
4             89.99          -0.507               1        -0.878
5            149.95          -0.383               5         2.153
6           2499.99           4.464               1        -0.878
7           1199.98           1.783               2        -0.120
8            539.94           0.421               6         2.911
9             51.98          -0.585               2        -0.120

In [54]:
# --- Exercise 9.3: MinMaxScaler (0-1 Normalization) ---
print("\n--- Exercise 9.3: MinMaxScaler (Range: 0-1) ---")

# Create copy for MinMaxScaler
df_minmax = df.copy()

# Initialize and fit MinMaxScaler
scaler_minmax = MinMaxScaler()
df_minmax[numerical_features] = scaler_minmax.fit_transform(df[numerical_features])

print(f"\n📊 After MinMaxScaler:")
print(df_minmax[numerical_features].describe().round(2))

print(f"\n💡 MinMaxScaler Characteristics:")
print(f"   - Min = 0")
print(f"   - Max = 1")
print(f"   - All values in range [0, 1]")
print(f"   - Sensitive to outliers")

# Compare original vs scaled
comparison_minmax = pd.DataFrame({
    'Original_Revenue': df['Total Revenue'].head(10),
    'MinMax_Revenue': df_minmax['Total Revenue'].head(10),
    'Original_Units': df['Units Sold'].head(10),
    'MinMax_Units': df_minmax['Units Sold'].head(10)
})

print(f"\n📊 Comparison (first 10 transactions):")
print(comparison_minmax.round(3))

--- Exercise 9.3: MinMaxScaler (Range: 0-1) ---

📊 After MinMaxScaler:
       Units Sold  Unit Price  Total Revenue
count      240.00      240.00         240.00
mean         0.13        0.06           0.08
std          0.15        0.11           0.12
min          0.00        0.00           0.00
25%          0.00        0.01           0.01
50%          0.11        0.02           0.04
75%          0.22        0.06           0.10
max          1.00        1.00           1.00

💡 MinMaxScaler Characteristics:
   - Min = 0
   - Max = 1
   - All values in range [0, 1]
   - Sensitive to outliers

📊 Comparison (first 10 transactions):
   Original_Revenue  MinMax_Revenue  Original_Units  MinMax_Units
0           1999.98           0.512               2         0.111
1            499.99           0.127               1         0.000
2            209.97           0.052               3         0.222
3             63.96           0.015               4         0.333
4             89.99           0.021               1         0.000
5            149.95           0.037               5         0.444
6           2499.99           0.640               1         0.000
7           1199.98           0.307               2         0.111
8            539.94           0.137               6         0.556
9             51.98           0.012               2         0.111

In [55]:
# --- Exercise 9.4: Side-by-Side Comparison ---
print("\n--- Exercise 9.4: StandardScaler vs MinMaxScaler ---")

comparison_both = pd.DataFrame({
    'Original_Revenue': df['Total Revenue'].head(10),
    'StandardScaler': df_standard['Total Revenue'].head(10),
    'MinMaxScaler': df_minmax['Total Revenue'].head(10)
})

print(f"\n📊 Three-Way Comparison (Total Revenue):")
print(comparison_both.round(3))

--- Exercise 9.4: StandardScaler vs MinMaxScaler ---

📊 Three-Way Comparison (Total Revenue):
   Original_Revenue  StandardScaler  MinMaxScaler
0           1999.98           3.433         0.512
1            499.99           0.339         0.127
2            209.97          -0.259         0.052
3             63.96          -0.561         0.015
4             89.99          -0.507         0.021
5            149.95          -0.383         0.037
6           2499.99           4.464         0.640
7           1199.98           1.783         0.307
8            539.94           0.421         0.137
9             51.98          -0.585         0.012

- Filtering
- Grouping
- Sorting
- Pivot
- Crosstab
- Merging